### ISSUE TITLE
analysis on imputed data

### ISSUE THREAD

**Issue by giovp** [Teichlab/cellphonedb#101]
Hi,

really nice and useful tool. I was wondering whether you tried or have any recommendation with respect to using imputed/denoised data as input. 
If no, what is the count threshold upon which cellphonedb filter % of cells expressing a gene? Is it just 0 (anything above is considered expressed) or something else (e.g. log(2))?

Thank you!
Giovanni

**Comment by mief** [comment]
Hi,
Thanks for your interest in our tool. We haven't tried using it with imputed data, so we can't give recommendation. It is possible that imputation can result into false-positive results (please see the paper here https://f1000research.com/articles/7-1740), so we prefer to use it on the normalised data.
The count threshold is 0, so everything above 0 is considered expressed.
Best,
Mirjana

**Comment by giovp** [comment]
Thanks a lot for the suggestion!
