### ISSUE TITLE
input cell labels as integers

### ISSUE THREAD

**Issue by ac3957** [Teichlab/cellphonedb#103]
When the meta and counts file have cell labels that are integers e.g. range(0, 2535), I get the following error:

[ERROR] Invalid Counts data: Some cells in meta didnt exist in counts columns. Maybe incorrect file format.

I checked that the labels in meta exactly match the labels in the counts columns. Replacing the labels with strings e.g. cell0, cell1. fixes this issue. There might be some type problem in parsing the input?

**Comment by mvento** [comment]
Hi @ac3957, 

Sorry for the inconvenience. Can you send us the input file (or a small part of that) to try to reproduce the error?

Thanks for using CellPhoneDB.

Best

**Comment by ac3957** [comment]
[test_meta_int.txt](https://github.com/Teichlab/cellphonedb/files/3453256/test_meta_int.txt)
[test_counts_int.txt](https://github.com/Teichlab/cellphonedb/files/3453257/test_counts_int.txt)

Here are your example files, with the cell labels replaced by the integers 1 through 10. I get the same error.

**Comment by mvento** [comment]
Hi @ac3957,

Sorry about the late reply. This bug will be fixed in the next release 1.2.1. We are going to release it this afternoon.
