### ISSUE TITLE
heatmap_plot

### ISSUE THREAD

**Issue by StephanTir** [Teichlab/cellphonedb#105]
Hi,

thanks for the great and very useful tool!

However, I have a problem when I try to generate the heatmap_plot. I get the following error:

> Error: Missing argument "meta-path".

Thanks for your help!

Best

Stephan

**Comment by StephanTir** [comment]
I found the solution here:
https://www.biorxiv.org/content/10.1101/680926v1.full

I need to set the path to the metadata file 

> cellphonedb plot heatmap_plot meta_data ...

You might want to add this to the Github repository README.md.

Best

Stephan

**Comment by mvento** [comment]
Hi @StephanTir, 

Thanks for using CellPhoneDB. You can check the example in the readme `cellphonedb plot heatmap_plot yourmeta.txt` (line 127 of README.md).

Best
