### ISSUE TITLE
Discrepancy between documentation and code, option --threshold

### ISSUE THREAD

**Issue by ToledoEM** [Teichlab/cellphonedb#106]
I really like the paper and this solution that you have done.
I found a discrepancy between the 'Readme.md' file, documentation (https://www.cellphonedb.org/documentation) and the code regarding the setting of the threshold of cells expressing a gene.
     
The threshold is stated in the documentation as the percentage (%) of cells but in code it is only accepted as a value between 0 and 1. 

Fixing the documentation to fraction would be the solution.    

Thank you.

```     

class ThresholdValueException(Exception):
    def __init__(self, threshold_value):
        super(ThresholdValueException, self).__init__(
            'Threshold value ({}) is not valid. Accepted range: 0<=threshold<=1'.format(threshold_value))
     
```
 https://github.com/Teichlab/cellphonedb/blob/master/cellphonedb/src/core/exceptions/ThresholdValueException.py

--- ERROR ---
> --threshold: % of cells expressing a gene
> [ ][APP][18/07/19-11:20:37][ERROR] Threshold value (20.0) is not valid. Accepted range: 0<=threshold<=1

**Comment by mvento** [comment]
Hi @ToledoEM, 

We updated the web documentation. Sorry for the inconvenience.

Thanks for your contribution.

Best
