### ISSUE TITLE
Mouse databases?

### ISSUE THREAD

**Issue by davisidarta** [Teichlab/cellphonedb#108]
Hi there! 

I found your manuscript and the database you've designed to be truly amazing!

I'm however confused. Is the current database available only for human data? One should build a similar database according to your instructions in order to do the analysis for mouse data?

**Comment by mvento** [comment]
Hi @davisidarta, 

Thanks for using CellPhoneDB. Actually, we only support human data. In the future, we will add more species to the database.

Sorry for the inconvenience.

Best

**Comment by qins** [comment]
Also want mouse database from 1 year later (✪ω✪)
