### ISSUE TITLE
different results between subsampled data and the complete data

### ISSUE THREAD

**Issue by yxiao832** [Teichlab/cellphonedb#109]
Hi, 
I recently tried cellphone DB on my subsampled data and the complete data and the results are different.

Here are the command I used for each:
cellphonedb method statistical_analysis /home/yxiao832/SeuratObject/NC_NASH_nuclei_3_9merge/metadata.txt /home/yxiao832/SeuratObject/NC_NASH_nuclei_3_9merge/Count_HumanID.txt --threads 12 --subsampling --subsampling-log false --subsampling-num-cells 3000

cellphonedb method statistical_analysis /home/yxiao832/SeuratObject/NC_NASH_nuclei_3_9merge/metadata.txt /home/yxiao832/SeuratObject/NC_NASH_nuclei_3_9merge/Count_HumanID.txt --threads 12

I can also send you the result if necessary. 

Thank you!
Yang

**Comment by lixin4306ren** [comment]
Have the same problem. Cell numbers of different clusters(cell populations) significantly affect the results. It seems that if some clusters have much more cells than other clusters, you usually get much more significant ligand-receptor interactions between some cluster pairs.  I don't know whether I should downsample those clusters.
