### ISSUE TITLE
Generate customized database

### ISSUE THREAD

**Issue by ahy1221** [Teichlab/cellphonedb#111]
Dear developers:
I was wondering that is that possible to generate my own database if I only have gene interaction table. 
It seems that `cellphonedb database generate` needs four data files. 
I think I can infer protein table and gene table by querying database like Uniprot. 
So the question might be how to generate complex table for cellphonedb, or is that table necessary ?

**Comment by mvento** [comment]
Hi  @ahy1221, 

Please, use `cellphonedb database generate --user-interactions your_custom_interaction_file.csv ` if you prefer to append your interaction file to CellPhoneDB interactions or `cellphonedb database generate --user-interactions your_custom_interaction_file.csv --user-interactions-only` yo use only your interactions file. 

For more information, please check the examples section:

https://github.com/Teichlab/cellphonedb#examples-for-user-specific-custom-database

Best

**Comment by mvento** [comment]
Hi @ahy1221, 

I forgot to comment, please, first update the cellphonedb package using `pip install --upgrade --no-cache cellphonedb` command.

Best
