### ISSUE TITLE
fail to run plot

### ISSUE THREAD

**Issue by fangling0913** [Teichlab/cellphonedb#114]
Hi, all
         I tried to use the example data to test if the cellphonedb has been installed correctly. I can successfully use the tool "method",but failed with the "plot". The error info is as follows. Can anyone help me?

R[write to console]: Error: package or namespace load failed for ‘methods’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/software/R-3.6.1/lib64/R/library/methods/libs/methods.so':
  /software/R-3.6.1/lib64/R/library/methods/libs/methods.so: undefined symbol: Rf_allocS4Object

R[write to console]: Error: package or namespace load failed for ‘utils’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/software/R-3.6.1/lib64/R/library/utils/libs/utils.so':
  /software/R-3.6.1/lib64/R/library/utils/libs/utils.so: undefined symbol: R_NilValue

R[write to console]: Error: package or namespace load failed for ‘grDevices’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/software/R-3.6.1/lib64/R/library/grDevices/libs/grDevices.so':
  /software/R-3.6.1/lib64/R/library/grDevices/libs/grDevices.so: undefined symbol: R_NilValue

R[write to console]: Error: package or namespace load failed for ‘graphics’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/software/R-3.6.1/lib64/R/library/grDevices/libs/grDevices.so':
  /software/R-3.6.1/lib64/R/library/grDevices/libs/grDevices.so: undefined symbol: R_NilValue

R[write to console]: Error: package or namespace load failed for ‘stats’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/software/R-3.6.1/lib64/R/library/grDevices/libs/grDevices.so':
  /software/R-3.6.1/lib64/R/library/grDevices/libs/grDevices.so: undefined symbol: R_NilValue

R[write to console]: Error: package or namespace load failed for ‘methods’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/software/R-3.6.1/lib64/R/library/methods/libs/methods.so':
  /software/R-3.6.1/lib64/R/library/methods/libs/methods.so: undefined symbol: Rf_allocS4Object

R[write to console]: During startup - 
R[write to console]: Warning messages:

R[write to console]: 1: package "methods" in options("defaultPackages") was not found 

R[write to console]: 2: package ‘utils’ in options("defaultPackages") was not found 

R[write to console]: 3: package ‘grDevices’ in options("defaultPackages") was not found 

R[write to console]: 4: package ‘graphics’ in options("defaultPackages") was not found 

R[write to console]: 5: package ‘stats’ in options("defaultPackages") was not found 

R[write to console]: 6: package ‘methods’ in options("defaultPackages") was not found 

R[write to console]: Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/software/R-3.6.1/lib64/R/library/methods/libs/methods.so':
  /software/R-3.6.1/lib64/R/library/methods/libs/methods.so: undefined symbol: Rf_allocS4Object

[ ][APP][05/09/19-08:20:40][ERROR] Unexpected error
Traceback (most recent call last):
  File "/software/Python-3.7.3/lib/python3.7/site-packages/cellphonedb/src/api_endpoints/terminal_api/plot_terminal_api_endpoints/plot_terminal_commands.py", line 72, in heatmap_plot
    pvalue=pvalue)
  File "/software/Python-3.7.3/lib/python3.7/site-packages/cellphonedb/src/plotters/r_plotter.py", line 36, in wrapper
    from rpy2 import robjects
  File "/software/Python-3.7.3/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 17, in <module>
    from rpy2.robjects.robject import RObjectMixin, RObject
  File "/software/Python-3.7.3/lib/python3.7/site-packages/rpy2/robjects/robject.py", line 58, in <module>
    class RObjectMixin(object):
  File "/software/Python-3.7.3/lib/python3.7/site-packages/rpy2/robjects/robject.py", line 70, in RObjectMixin
    __show = _get_exported_value('methods', 'show')
  File "/software/Python-3.7.3/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py", line 28, in _
    cdata = function(*args, **kwargs)
  File "/software/Python-3.7.3/lib/python3.7/site-packages/rpy2/rinterface.py", line 773, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/software/R-3.6.1/lib64/R/library/methods/libs/methods.so':
  /software/R-3.6.1/lib64/R/library/methods/libs/methods.so: undefined symbol: Rf_allocS4Object

**Comment by mvento** [comment]
Finally soved using docker image:
https://hub.docker.com/r/ydevs/cellphonedb

For old systems (eg: Centos 6.X), please, use stretch image.
