### ISSUE TITLE
should the input data be raw data or normalized data?

### ISSUE THREAD

**Issue by ZenobiaDing117** [Teichlab/cellphonedb#12]
When I use normalized data as input(data from `seurat` with log format), I found the output contained only very few genes( only 18 genes ). I think it might be caused by negative value in the normalized input. So I change to use raw data as input and get 1873 genes in deconvoluted.txt, but I wonder whether cellphone will normalize it or not? Thank you for your work and look forward for your reply^_^

**Comment by flde** [comment]
Many thanks for the great tool! Just to clarify, the setting is relative counts (divide by total UMI times a scaling factor)? Many thanks!
