### ISSUE TITLE
 Unable to save dotplot

### ISSUE THREAD

**Issue by aditisk** [Teichlab/cellphonedb#120]
Hello,

I am trying to use the dot_plot function but I am unable to save the plot. The plot appears for a quick second on my screen but disappears after that. The output directory gets created with the specified name but the directory has nothing in it.

Please let me know how to fix this and if I am missing anything from the documentation.

Thanks.

**Comment by mvento** [comment]
Hi @aditisk, 

This is is a MacOS bug when pdf is generated. You can try with other formats setting the name. Ex:
```
cellphonedb plot dot_plot --output-name your_custom_name.png
```

If you need to export to pdf, we highly recommend use docker instance: 

https://cloud.docker.com/u/ydevs/repository/docker/ydevs/cellphonedb


Best

**Comment by yuzhouevelyntong** [comment]
I solved this problem by downloading XQuartz to MAC

https://www.xquartz.org
