### ISSUE TITLE
receptor_a and receptor_b are the same True/False

### ISSUE THREAD

**Issue by Lijinluu** [Teichlab/cellphonedb#122]
Hi,thanks for your great database and tool . When i was  using  the cellphonedb to predict  functional interactions, I found some interacting_pair have the same annotation (True True  or False False )  at receptor_a and  receptor_b column   in significant_means.txt file. 

Just like that:
`CPI-SC0C3E2D267 F10_aMb2 complex        simple:P00742   complex:aMb2 complex    ENSG00000126218         True    False   False   curated  ,,, `

Would you please tell me  what they mean? Thank you  very much.

**Comment by 1746252547** [comment]
attention

**Comment by keenhl** [comment]
I think it means, and I could definitely be wrong, that there is a receptor-receptor or ligand-ligand interaction.   For example, there are a lot of receptors can that make hetero-dimers.

**Comment by Momomocheng** [comment]
attention

**Comment by youarespecial** [comment]
Sorry , I still don't understand how to understand this ? Can someone explain it more clearly?

**Comment by keenhl** [comment]
@youarespecial Can you explain specifically what you didn't understand.
