### ISSUE TITLE
All lines from the Counts file were filtered

### ISSUE THREAD

**Issue by Lyuzu** [Teichlab/cellphonedb#124]
Dear Developer:
I am trying "cellphonedb" on my single cell data. I met a problem when I wanted to test the small data provided on your webpage. "All the lines were removed". I can not figure out what the problem is because I just  put the test data into the two slots and choose "ensembl" . There  seems like a simple problem I don't notice.  I also tried my own data(much more cells), the problem was the same.
Looking forward to your reply. Thank you.
![image](https://user-images.githubusercontent.com/42428287/66251952-a4534580-e788-11e9-8f20-31e8e2c6633d.png)

**Comment by mvento** [comment]
Hi @Lyuzu, 

Thanks for using CellPhoneDB. Are you using Human data? Can you send me the input data?

Best

**Comment by aleph9999** [comment]
I also face the same issue, and it can't even work with the sample input and meta provided on the site (using ensemble gene name). Is there anything wrong on the default setting? Thanks for help!

**Comment by mvento** [comment]
Hi, 

We fixed it yet. Sorry for the inconvenience.

Best!
