### ISSUE TITLE
ValueError: You are trying to merge on float64 and object columns.

### ISSUE THREAD

**Issue by cartal** [Teichlab/cellphonedb#125]
Hi, I'm also getting: 

`ValueError: You are trying to merge on float64 and object columns. If you wish to proceed you should use pd.concat`

I'm using `cellphonedb==2.1.1` and I get the same error after followed your instructions as above; any ideas?

_Originally posted by @cartal in https://github.com/Teichlab/cellphonedb/issues/21#issuecomment-541653074_

**Comment by mvento** [comment]
Hi @cartal, 

Thanks for using CellPhoneDB. Can you send us the input files? 

Best

**Comment by cartal** [comment]
Hi @mvento , 
I just sent you an email with access to the toy example.

**Comment by ltongyu** [comment]
Hi, I wonder if this problem has been solved. I got the same error.

**Comment by mvento** [comment]
Hi @cartal, 

The problem is in your Counts file. It have Gene column but the values are always 0. 

Please, set this data and retry.

Best

**Comment by mvento** [comment]
Hi @ltongyu, 

Can you check if your Gene column data in Counts file is correct?

Best

**Comment by ltongyu** [comment]
> Hi @ltongyu,
> 
> Can you check if your Gene column data in Counts file is correct?
> 
> Best

Yes, I solved the problem by correcting gene column. Thank you.

**Comment by XiaoyuLi-smu** [comment]
I had the same error. I was using the example data and the version is 2.1.2. The only problem might be i was using my own interaction database but it was build without error.

**Comment by DongqingSun96** [comment]
Hi @XiaoyuLi-smu, have you solved this problem?

**Comment by XiaoyuLi-smu** [comment]
no, thx



---Original---

**Comment by jmrussell** [comment]
I am still getting this error on the latest cpdb release with a counts value has many non-zero values
