### ISSUE TITLE
Error: Result is empty

### ISSUE THREAD

**Issue by Matthias3033** [Teichlab/cellphonedb#127]
Hi,
when I run the statistical analysis in cellphonedb, I get the following error message: **Result is empty**. My data comes from an anndata object out of scanpy. Many thanks in advance for your help.

Technical data:
Windows 10
Python 3.6.8
Cellphonedb v.2.0.0

**Comment by mvento** [comment]
Hi @Matthias3033 can you send the input files?

Best

**Comment by Matthias3033** [comment]
Hi @mvento,

here is an excerpt of my used data 
[Data_cellphonedb.zip](https://github.com/Teichlab/cellphonedb/files/3807860/Data_cellphonedb.zip)


Best

**Comment by Matthias3033** [comment]
Hi @mvento,

I was able to solve the problem by converting the gen names to ens ids.

Best

**Comment by ruohuchengxhe** [comment]
> Hi @mvento,
> 
> I was able to solve the problem by converting the gen names to ens ids.
> 
> Best

Hi Matthias! Good to know you converted gen names to ens ids. I was not able to do this. May I ask how did you convert them? Thanks you!
Best
