### ISSUE TITLE
Having trouble using the function cellphonedb plot

### ISSUE THREAD

**Issue by daisyyr** [Teichlab/cellphonedb#129]
**It's my first time to use cellphonedb. I have no problem using cellphonedb method.
While I was using cellphonedb plot with the code "cellphonedb plot dot-plot  "

It showed errors as follows:**

R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
https://www.gnu.org/licenses/.

As there is no R environment set up, some functionalities will be disabled, e.g. plot
R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
https://www.gnu.org/licenses/.

You cannot perform this plot command unless there is a working R setup according to CellPhoneDB specs

So what can I do with this situation? I have already installed R (version 3.6.1)
Thanks~

**Comment by keenhl** [comment]
Do you know if you have the package ggplot2 installed in R?

**Comment by CharleneZ95** [comment]
Set environment for R solved this, 
 <pre>
export PATH=/path/to/R/:$PATH
cellphonedb plot dot_plot --rows in/rows.txt --columns in/columns.txt
</pre>
Hope this helps~

**Comment by mvento** [comment]
@daisyyr Did you fix this issue? 

If it didn't work well, you can try to use this docker image https://hub.docker.com/r/ydevs/cellphonedb 

Best
