### ISSUE TITLE
[ERROR] Invalid Counts data 

### ISSUE THREAD

**Issue by cyanching** [Teichlab/cellphonedb#130]
Hey there! I am new to cellphonedb, I have tried to export my normalised count data into the same format as the example you have then run the statistical_analysis method on my meta and count files, but I keep getting the error: Invalid Counts data, I have called count data from my Seurat object, then wrote a txt table:

`human_count <- human.Seurat@assays$RNA@counts %>% as.data.frame() %>% rownames_to_column() %>% rename(Gene = rowname)`

`write.table(human_count,"human_count_integrated_30PC.txt",sep="\t")`

Is there anything I did wrong? Could you suggest a solution?

**Comment by keenhl** [comment]
Is the column order in the counts file the same as the row order in the meta file?

**Comment by cyanching** [comment]
Hey keenhl, thank you for your reply! I already solved the issue by adjusting the formating of my count file!

**Comment by keenhl** [comment]
Good.  Thanks for the update.

**Comment by singcell** [comment]
@cyanching Can you share how your formatting solved the problem. i have the same issue.

**Comment by cyanching** [comment]
> @cyanching Can you share how your formatting solved the problem. i have the same issue.

I corrected the format of my count file, so I have (1,1) as 'Gene', then filed the first col with ensemble gene ID, the first row with cell ID, the rest with count data.

**Comment by zhanglab2008** [comment]
> > @cyanching Can you share how your formatting solved the problem. i have the same issue.
> 
> I corrected the format of my count file, so I have (1,1) as 'Gene', then filed the first col with ensemble gene ID, the first row with cell ID, the rest with count data.

Great tip! I also had the same error when I ran the codes from the Nature Protocol paper. I solved it using your methods. Thanks!
