### ISSUE TITLE
dot plot

### ISSUE THREAD

**Issue by paolo-kunderfranco** [Teichlab/cellphonedb#133]
Dear All,
I am facing some problems producing the dot plot after running my cellphone to my single cell data.

1)default option --> pdf
File is opened in adobe, but it warns that is to big and so is truncated

2) option jpeg and png
rror in grDevices::png(..., res = dpi, units = "in") :
  unable to start device 'png'

R[write to console]: Warning message:
R[write to console]: In grDevices::png(..., res = dpi, units = "in") :
R[write to console]:
R[write to console]:  cairo error 'invalid value (typically too big) for the size of the input (surface, pattern, etc.)'
[ ][APP][04/12/19-10:53:50][ERROR] R Runtime Exception: Error in grDevices::png(..., res = dpi, units = "in") :
  unable to start device 'png'

How can I resolve these issues?
Is there a way to save to ggplot2 file?

Many Thanks
Paolo

**Comment by keenhl** [comment]
The R code that produces the plot is found in the following file.  I think you should be able to modify the file to save the plot as a ggplot2 object.  If I get a chance, I will try and report back.  

cellphonedb/cellphonedb/src/plotters/R/plot_dot_by_column_name.R

**Comment by mvento** [comment]
Hi @paolo-kunderfranco, 

Thanks for using CellPhoneDB. Did you finally implement the plot using ggplot2 library? 

If you did it, we can include it in CellPhoneDB official repo.

Best!
