### ISSUE TITLE
Prioritize results

### ISSUE THREAD

**Issue by keenhl** [Teichlab/cellphonedb#135]
Hi all,

I ran the cellphoneDB analysis with the default parameters and there were lot of interactions with p-value equal to 0.  My question is how do I further prioritize this list.  Should I do more than 1000 permutations so that I can get p-values with greater precision or should  I use the means values to sort the list of significant interactions.  

Any thoughts.

Thank you very much.

**Comment by mief** [comment]
Hi,
For prioritising interactions, you can use the significant_means table where the interactions are ranked based on the number of significant p-values. Another possibility is to be stricter with the expression level threshold and set it to 20% or higher.

Best,
Mirjana
