### ISSUE TITLE
How to use user defined ligand-receptor datasets

### ISSUE THREAD

**Issue by wwn7268** [Teichlab/cellphonedb#137]
Hi CellphoneDB team,

I want to infer cell-cell communication with my owe database. I try to use the code below.

 cellphonedb database generate --user-interactions your_custom_interaction_file.csv --user-interactions-only

So what kind of csv file should I input?  Could you show me an example of this csv file. Thank you very mauch!

Best

**Comment by mvento** [comment]
Hi @wwn7268, 

You use the original as example:
https://github.com/Teichlab/cellphonedb-data/tree/master/data 

[Here](https://www.biorxiv.org/content/biorxiv/early/2019/06/24/680926/F4.large.jpg) you can check the mandatory columns and the process. 

Best!
