### ISSUE TITLE
large sparse matrix as input

### ISSUE THREAD

**Issue by bio-la** [Teichlab/cellphonedb#138]
Hi, thanks for the great tool!
would it be possible to accept large matrices in the mtx format instead of txt? or did you think of a fast routine to convert sparse matrices to an input that the tool would accept? 
I am writing my large matrix to txt using a mix of R and numpy/pandas but it takes forever so maybe I'm doing something wrong.
thank you!
biola

**Comment by msmicker** [comment]
Hello, I am also interested in this. I am dealing with very large datasets. While it is possible to create a dense matrix I am curious about the limitations for cellphonedb to analyze even with subsampling. Is there experience with very large datasets? e.g. more than 100k cell? While I am able to export all of my datasets in dense matrix it is time consuming and also failing with any datasets larger than ~150k cells.

**Comment by Dzhan4** [comment]
Also curious about this. I was going to try to save sparse matrix `as.data.frame(as.matrix(sparsematrix))` into a .txt file. I imagine this will take a long time. Anyone else have any ideas?

**Comment by rrydbirk** [comment]
I'm also listening in on this. It doesn't seem reasonable to write to .txt from a sparse matrix, in my case with ~3.4 billion fields...

**Comment by bjstewart1** [comment]
ideally both sparse matrix and anndata input rather than needing to store as .txt

**Comment by J-Keding** [comment]
I had the same issue with my sparse matrix that I extracted from a seurat object. I can reccomend looking at the _write_dgCMatrix_csv_ function from the _scrattch.io_ package, which writes the dgCMatrix to a CSV in chunks, thus saving time and memory.

**Comment by onahman** [comment]
+1 from me. It would be great to if you allow direct transfer of dataframe / matrices !
I tried to change the code myself but the FLASK API is a bit over my head
