### ISSUE TITLE
How to calculate the forceNetwork between cells based on the results of cellphonedb？

### ISSUE THREAD

**Issue by panxiaoguang** [Teichlab/cellphonedb#139]
How to calculate the forceNetwork between cells based on the results of cellphonedb

**Comment by mief** [comment]
Do you mean force-directed layout, as we did in the publication? We inputed the two network files you will get when plotting the heatmap into Cytoscape where you can set the force-directed layout.

**Comment by Mohebg1234** [comment]
@mief Can you please let me know how to do this with cellphonedb output ?
Thanks alot
