### ISSUE TITLE
Heatmap order of cells

### ISSUE THREAD

**Issue by rlorenzc** [Teichlab/cellphonedb#143]
Hi!

Is there a way to tell cellphoneDB a specific way to order the heatmap rows and columns? I'm trying to compare two datasets and it always generates heatmaps that have some hierarchical clustering done on them.

Similarly, what is the output file being parsed into pheatmap? I can also just plot that object onto pheatmap to get the order of the columns and rows in a specific way.

Thanks!

Lorenz

**Comment by mvento** [comment]
Hi @rlorenzc, 

Thanks for using CellPhoneDB. It didn't exist a way to sort rows/columns in the plots right now. 

Please, feel free to implement it (and share! 🙃). 

[Here](https://github.com/Teichlab/cellphonedb/tree/master/cellphonedb/src/plotters/R) you can find the R plot files. You can call directly from R Studio. 

Best!
