### ISSUE TITLE
How would one make a circos plot to show all interactions with a p-value below a threshold

### ISSUE THREAD

**Issue by kaizen89** [Teichlab/cellphonedb#146]
Hi,
I would like to know it it is possible to use the pvalues files to make a Circos plot showing all significant interactions between different clusters with each interaction line being a ligand-receptor pair.
something like this
![image](https://user-images.githubusercontent.com/30392707/75447904-85896180-596a-11ea-99f6-a511a82df0d9.png)

**Comment by mvento** [comment]
Hi @kaizen89, 

Thanks for the proposal. We will try to implement it in the future. 

If you want to contribute, please, feel free to implement it in R or Python. It makes easier to add it to the CellPhoneDB core. 

Best!
