### ISSUE TITLE
Document 3: significant mean. (significant_mean.csv)

### ISSUE THREAD

**Issue by sunshine-lp0** [Teichlab/cellphonedb#15]
Hi all,
What's the **'rank'** mean in output file 3(Document 3: significant mean. (significant_mean.csv))?
Thank you.

**Comment by xxl619755841** [comment]
> Hi,
> The rank is calculated by counting the significant p-values per interaction pair (per row) and dividing with the total number of cluster-cluster comparisons. The idea is to prioritize interactions that are highly specific, that is they have only one or few significant p-values and to have on the bottom of the list the interactions that are present everywhere or not present anywhere at all.
> I hope this helps and please let us know if you have any questions or issues.
> Best,
> Mirjana

Hi mief:
Your answer is helpful to me.  And I want to know why there are ranks greater than 1 in the result? The max rank is 1 in my understanding of it. There is any misunderstanding about it?
Thanks!

**Comment by jad362** [comment]
> Hi mief:
> Your answer is helpful to me. And I want to know why there are ranks greater than 1 in the result? The max rank is 1 in my understanding of it. There is any misunderstanding about it?
> Thanks!

Hi, just wanted to add that I am also questioning this as I have a large number of interactions with rank > 1 which does not make sense to me. Any help with this would be greatly appreciated!
Thanks!

**Comment by mief** [comment]
Hi,
For the interaction pairs that don't have any significant p-values, instead of the rank being 0 (this would make them ranked highest), we put the rank to be 1+max(rank) so that they can be ranked on the bottom of the list. I hope this helps.
Mirjana
