### ISSUE TITLE
Cellphonedb with multiple samples in one group

### ISSUE THREAD

**Issue by polojacky** [Teichlab/cellphonedb#152]
Nice work!
Recently I read a paper which uses cellphonedb in its analysis (https://doi.org/10.1038/
s41591-019-0468-5) to compare the different interactions between the two groups. In the paper, multiple samples are used in each group. 

I noticed the cellphonedb tutorial doesn't mention the situation when multiple samples are included in one analysis, which is common in scrna-seq analysis.  I think the best way is running the analysis individually and then getting the common interaction between the samples, just like celltalker(https://arc85.github.io/celltalker/) does.

What's your suggestion?

**Comment by yaolutian** [comment]
want an answer too, currently I am doing your way.

**Comment by mief** [comment]
Hi,

Thanks for your interest in our tool! For now, we are also running the method separately on two conditions/samples and look for interactions that are enriched in one condition and not in the other. We have tried this in a recent paper for analysis of healthy lung vs asthma.

Best,
Mirjana
