### ISSUE TITLE
Filtering criteria when uploading counts file?

### ISSUE THREAD

**Issue by tinjac** [Teichlab/cellphonedb#153]
Hej!

I am using your web interface at https://www.cellphonedb.org/explore-sc-rna-seq and have troubles uploading my scRNAseq data.

I have a murine dataset, but have translated all gene names to human gene names. Still, about 9200 of my 9700 genes get filtered and it's not obvious to me what is the filtering criteria.

Could you please shortly explain what criteria are used to filter genes? 

I have attached my count file. It's highly simplified. Includes only 4 cells (columns) instead fo 1500 but I thought it would still be good to include it in case there is some systematic error I don't see. Of course I can provide the original table if needed.

[Example_cellphonedb_count.txt](https://github.com/Teichlab/cellphonedb/files/4383030/Example_cellphonedb_count.txt)

Thanks for your help!
Best regards!

**Comment by mief** [comment]
Hi,
I managed to run the analysis with your data, and a fictional meta data, here is a screen shot
![image](https://user-images.githubusercontent.com/29858930/77741594-0e98c480-700d-11ea-8c12-969140149192.png)
We filter the dataset for all the receptor/ligands that are included in the dataset. You can download those from our Downloads page / CellPhoneDB lists.
I hope this helps and let us know if you're still having problems.
Best,
Mirjana

**Comment by tinjac** [comment]
Thanks for your answer, Mirjana!

I was not aware that already during the upload step genes that are neither receptor nor ligand are filtered out. That explains why my upload worked in principle but so many rows got filtered.

**Comment by life-gif** [comment]
Hi I am running human scRNA data 
got this error
Any idea what happened?

[ ][APP][07/05/20-16:56:33][ERROR] All counts filtered: Are you using human data?.

**Comment by danshu** [comment]
@life-gif  I also got this error and I found out that I haven't set "--counts-data [ensembl|gene_name|hgnc_symbol]"

**Comment by life-gif** [comment]
Thanks a lot ! danshu
Does this look correct to you? still getting error :(
cellphonedb method analysis Tumormetadata.txt Tumor.count.txt--counts-data [hgnc_symbol]

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/utils/deprecation.py:143: FutureWarning: The sklearn.cluster.k_means_ module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.cluster. Anything that cannot be imported from sklearn.cluster is now part of the private API.
  warnings.warn(message, FutureWarning)
[ ][APP][08/05/20-11:01:56][WARNING] Latest local available version is `v2.0.0`, using it
[ ][APP][08/05/20-11:01:56][WARNING] User selected downloaded database `v2.0.0` is available, using it
Usage: cellphonedb method analysis [OPTIONS] META_FILENAME COUNTS_FILENAME

Error: Got unexpected extra argument ([hgnc_symbol])

**Comment by life-gif** [comment]
never mind! I fixed the problem! it is running now. :-)
