### ISSUE TITLE
Can we use only subsets of interaction pairs

### ISSUE THREAD

**Issue by qingnanl** [Teichlab/cellphonedb#154]
Dear team,

Thanks for the beautiful work. I am wondering, is it possible that we can still use your database, but only use a subset of it? For example, we only care about neurotransmission in some cases. Can we specify what pairs we do want to compute for (as input)?

Thanks,

qingnanl

**Comment by mief** [comment]
Hi Qingnanl,

Thanks for your interest in our work! Yes, you can generate your own custom database using the generate command and specify that you would like to use only those interactions: 
cellphonedb database generate --user-interactions your_custom_interaction_file.csv --user-interactions-only

 https://github.com/Teichlab/cellphonedb#generating-user-specific-custom-database

I hope this helps,
Mirjana
