### ISSUE TITLE
threads option - how to reduce runtime?

### ISSUE THREAD

**Issue by bio-la** [Teichlab/cellphonedb#155]
Hi,
I'm trying to understand how to set threads param in order to reduce the runtime. 
I'm happy to subsample the dataset enabling the subsampling option, but at the moment I specify threads 4 and it doesn't make a difference in terms of runtime : 15k cells or 1500 cells will take 14 hrs to be analysed with cellphonedb method statistical_analysis.
I can increase the number of threads but it didn't seem to make a difference either.

full set of params:

`cellphonedb method statistical_analysis ${OUTPATH}/meta_info.txt ${OUTPATH}/Gene_counts.txt --output-path ${OUTPATH}/${OUTPATH}.results --threads 4 --subsampling --subsampling-log False --subsampling-num-pc 100 --subsampling-num-cells 1500`

any suggestion?
thanks!!

**Comment by jmrussell** [comment]
It's because the argument is --threads=4 not just threads 4

**Comment by bio-la** [comment]
are you sure? it gets picked up by cellphonedb anyway...

[ ][CORE][01/04/20-14:23:03][INFO] [Cluster Statistical Analysis Simple] Threshold:0.1 Iterations:1000 Debug-seed:-1 Threads:4 Precision:3
