### ISSUE TITLE
Plot problem

### ISSUE THREAD

**Issue by hexingkang1990** [Teichlab/cellphonedb#156]
Hi when I tried to rum command 'cellphonedb plot dot_plot', it had some problem. it showed "File "/Users/macpro/cpdb-venv/lib/python3.7/site-packages/rpy2/rinterface.py", line 773, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error: package or namespace load failed for ‘ggplot2’ in library.dynam(lib, package, package.lib):
 shared object ‘rlang.dylib’ not found".
I serached and found it might be  problem of loading ggplot2. but I don't know how to solved it.
thanks.
bests,
xingkang

**Comment by mief** [comment]
Hi,
Do you have the R package ggplot2 installed?
