### ISSUE TITLE
plot problem

### ISSUE THREAD

**Issue by millersan** [Teichlab/cellphonedb#158]
Hi,
I try to used the test file: "row.txt" "column.txt" to finished the dotplot. But it returns to this error.
I wonder if you could help me with this

+++++++++++++++++++++++++++++++++++++++++++++++++
R[write to console]: Registered S3 methods overwritten by 'ggplot2':
  method         from
  [.quosures     rlang
  c.quosures     rlang
  print.quosures rlang
R[write to console]: Error in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y,  :
  invalid font type
R[write to console]: In addition:
R[write to console]: There were 50 or more warnings (use warnings() to see the first 50)
R[write to console]:
[ ][APP][09/04/20-01:35:23][ERROR] R Runtime Exception: Error in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y,  :
  invalid font type
++++++++++++++++++++++++++++++++++++++++++++++++++

here is my code
###########################################################
cellphonedb plot dot_plot --pvalues-path=./out/pvalues.txt --means-path=./out/means.txt  --output-path=./out --output-name=dotplot.pdf --rows ./in/example_data/rows.txt --columns ./in/example_data/columns.txt
###########################################################

thanks.
bests,
millersan

**Comment by millersan** [comment]
I finished the result from the "cellphonedb/cellphonedb/src/plotters/R/plot_dot_by_column_name.R"
^_^

**Comment by mief** [comment]
Hi,
Was the problem with the font? We put 'Arial' by default, but we will change this.
Thanks,
Mirjana
