### ISSUE TITLE
sklearn.cluster update?

### ISSUE THREAD

**Issue by chrsyl** [Teichlab/cellphonedb#159]
Hello,
I am new to CellphoneDB and it looks very exciting!
However, after downloading and installation this message came up:
/Users/chrsyl/cpdb-venv/lib/python3.8/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.cluster.k_means_ module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.cluster. Anything that cannot be imported from sklearn.cluster is now part of the private API.   warnings.warn(message, FutureWarning)
Can I get a hint on how to update?

**Comment by life-gif** [comment]
Hi Chryl, 
I am getting the same message. Did you solve the issue?

**Comment by chrsyl** [comment]
No, could not solve it ;(

11 maj 2020 kl. 20:32 skrev life-gif <notifications@github.com>:

﻿

Hi Chryl,
I am getting the same message. Did you solve the issue?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTeichlab%2Fcellphonedb%2Fissues%2F159%23issuecomment-626877926&data=02%7C01%7Cchrister.sylven%40ki.se%7C3ceba5454d694a76c6e808d7f5d99822%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637248187219996416&sdata=Dwg%2FmSIDWkVjb3aTFRalpBMAywhuT1a%2BpBT%2BvLGnazc%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABXFFREUV2ZNT6776TKRYPLRRBAB7ANCNFSM4MHDKVSQ&data=02%7C01%7Cchrister.sylven%40ki.se%7C3ceba5454d694a76c6e808d7f5d99822%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637248187219996416&sdata=dWl8ht2OmZHg0Yk%2Fr4OvVJirxe8zIC%2B6pm%2FMOW3T0DY%3D&reserved=0>.



När du skickar e-post till Karolinska Institutet (KI) innebär detta att KI kommer att behandla dina personuppgifter. Här finns information om hur KI behandlar personuppgifter<https://ki.se/medarbetare/integritetsskyddspolicy>.


Sending email to Karolinska Institutet (KI) will result in KI processing your personal data. You can read more about KI’s processing of personal data here<https://ki.se/en/staff/data-protection-policy>.

**Comment by renzorock** [comment]
Hi @chrsyl @life-gif ... I think it is just a warning. I had a similar warning but the later commands should run smoothly.

**Comment by hartmannmark** [comment]
Hi. I get the same error message when I try to run the dotplot or heatmap functions. As a consequence, I can't find the plot neither in the output directory nor anywhere else. Even though the plot pops up briefly... 
Any help?

`cellphonedb plot dot_plot
The sklearn.cluster.k_means_ module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.cluster. Anything that cannot be imported from sklearn.cluster is now part of the private API.`

**Comment by zexllin** [comment]
me too

**Comment by prete** [comment]
That's a `FutureWarning` not an error, despite the message you get everything _should_ be working properly.

A warning tends to be a notice (either from the compiler or a library) that **does not imply a fatal error**. It's something that could go wrong or, like this case, something that might not work in the future (ie. deprecation).

**Comment by hartmannmark** [comment]
> That's a `FutureWarning` not an error, despite the message you get everything _should_ be working properly.
> 
> A warning tends to be a notice (either from the compiler or a library) that **does not imply a fatal error**. It's something that could go wrong or, like this case, something that might not work in the future (ie. deprecation).

But unfortunately it does not work properly, as mentioned above. The plots are not saved anywhere, the output directory is empty.

**Comment by blackturtle-bam** [comment]
Hello, I have the same issue. I cannot find the plot in the output directory. Did anyone solve the issue?

**Comment by prete** [comment]
`cellphonedb plot dot_plot` requires R packages installed and visible to the tool
@blackturtle-bam if you create a new conda environment using `environemnt.yml` from #270 do you still have the same issue?

**Comment by blackturtle-bam** [comment]
> `cellphonedb plot dot_plot` requires R packages installed and visible to the tool
> @blackturtle-bam if you create a new conda environment using `environemnt.yml` from #270 do you still have the same issue?

Thank you for the suggestion. I solved the problem by exporting as jpg. It turns out to be related to the MacOS bug when pdf is generated #120

**Comment by prete** [comment]
`sklearn.cluster.k_means_ module is deprecated in version 0.22 and will be removed in version 0.24` is not related to any plotting issues. If plotting is not working for you, check:
- you've got the right packages/dependencies for plotting (R/ggplot2/pheatmap)
- try plotting to a different format other than PDF (JPG/PNG).
