### ISSUE TITLE
Document 1: p-value (pvalues.csv)

### ISSUE THREAD

**Issue by sunshine-lp0** [Teichlab/cellphonedb#16]
Hi all,
Great tool! 
Why the range of **p-value** in paper **Single-cell reconstruction of the early maternal–fetal interface in humans** are 0, 1, or 0-0.9(**Supplementary Table 4 - List of interactions in the placenta dataset**). There were no values such as 0.02, 0.001 and so on. But in **Fig.5A**, the legend "**-log10(P-value)**" includes **0, 1, 2, >=3**.
[https://www.nature.com/articles/s41586-018-0698-6](url)
Thanks

**Comment by mief** [comment]
Hi,
Thanks for the nice comments! In our new version, the p-values are now with more decimals and  you can use the --result-precision parameter to set the number of decimals. I hope this helps and please let us know if you have any other issues.
