### ISSUE TITLE
dot/heatmap_plot core dumped

### ISSUE THREAD

**Issue by wangjiawen2013** [Teichlab/cellphonedb#165]
Dear,

When I try "cellphonedb plot dot_plot" and "cellphonedb plot heatmap_plot meta_data" on test data, the following error occurred:
Segmentation fault (core dumped)

last week I ran this code successfully, but today it didn't work. I tried it again on my MacOS, the heatmap looks good, but the dot plot looks weired:
![QQ图片20200423174939](https://user-images.githubusercontent.com/29703450/80085744-40a93200-858b-11ea-9e42-6e1777107f85.png)

Then I copied the source code of dot_plot(), and ran it in R environment on my Centos7 server, the plot.pdf could be generated, but it also looks weired, it's the same as that generated by MacOS. Finally I changed the width and height parameter of dot_plot() function, the plot looked pretty, so maybe there are something when integrating dot_plot() and heatmap_plot() function into cellphoneDB or it cannot process too many interactions (~1000 ligand-receptor interactions).

Could you give me some advice ?

**Comment by mief** [comment]
Hi,

By default the dot plot has width of 8 and height of 10, so if you input many interactions, those dimensions are too small and need to be changed, like you did.

Best,
Mirjana
