### ISSUE TITLE
How do you use only the ligand-receptor pairs for analysis？

### ISSUE THREAD

**Issue by Rui-Jing** [Teichlab/cellphonedb#166]
Hi,thanks for your great database and tool . CellPhoneDB is suitable for the analysis of human samples. 
When I want to analyze a sample of mice, how do I analyze it? I currently have only one file containing three columns of receptors and ligands, one column is the name of the receptor genes, the other column is the name of the ligand genes, and the last column is the ligand-receptor binding pairs. I don’t know what else I should do to analyze mouse samples with CellPhoneDB？

I am looking forward to receiving your reply. Thank you very much.

**Comment by mief** [comment]
Hi,

For mouse data, we use the ortholog genes, downloaded from biomart. We convert the mouse genes into their human orthologs and input that into the tool.

I hope this helps,
Mirjana
