### ISSUE TITLE
Can CellPhoneDB run through RStudio?

### ISSUE THREAD

**Issue by ChonkyPotato** [Teichlab/cellphonedb#167]
Hi, 
I've recently started scRNA analysis and am learning to use RStudio. 
I was wondering if its possible // how to use this package in RStudio?
I do have the 'reticulate' package installed, but I'm not sure how to install cellphonedb.
Any info would be appreciated!

**Comment by chrsyl** [comment]
Yes,
google: cellphone_for_seurat
Best

**Comment by ChonkyPotato** [comment]
Thank you
