### ISSUE TITLE
Details on orthology conversion

### ISSUE THREAD

**Issue by HyacintViolet** [Teichlab/cellphonedb#171]
Hi. Thanks for building this excellent tool!
I have a scRNAseq dataset with mouse genes. When I try to convert them to human orthologs, I ran into some trouble.

I used R package "biomaRt" to perform the gene conversion, however I found many duplicates in the results. I figured that this is due to multi-mapping orthologs during the conversion procedure.

For example, a single gene in mouse (i.e. "ENSMUSG00000024107") can be mapped to two genes ("ENSG00000279956" and "ENSG00000138039") in human,

and multiple mouse genes (i.e. "ENSMUSG00000059498" and "ENSMUSG00000026656") can be mapped to a single human gene ("ENSG00000143226").

In the worst case, multiple mouse genes ("ENSMUSG00000019122" and "ENSMUSG00000018927") gets mapped to multiple human genes ("ENSG00000274736", "ENSG00000275688", and "ENSG00000275718").

I am wondering whether cellphoneDB accepts duplicate rownames? If not, what was your solution to this?

**Comment by mief** [comment]
Hi,

Thanks for your interest in our tool! We don't accept duplicates in the input. One option would be to use only one-one orthologs. Our strategy so far has been to take the one with the max mean expression and keep that one.

I hope this helps,
Mirjana
