### ISSUE TITLE
just a suggestion for ligand and receptor order

### ISSUE THREAD

**Issue by ChickenWangSY** [Teichlab/cellphonedb#172]
Hi, I just found that some interactions were that ligand come first and receptor come back ,like IGF1_IGF1R,and some interactions were opposite, like EGFR_EGF. when I split all clusters' interaction by receptor clusters, I found that some ligand clusters involved in that. what do you think about setting uniform order,like ligand_receptor ?

**Comment by monkeyBai96** [comment]
I concur.

**Comment by yanxiting** [comment]
I have the same issue. It is preventing good results interpretation and demonstration. 

In the pvalues.txt, it does have receptor_a and receptor_b to tell whether they are receptor or not. But there are many pairs with both receptor_a and receptor_b being true or both are false. This means that these two columns cannot be used to decide which is ligand and which is receptor.

It would be awesome if this can be fixed. Thanks!

**Comment by mief** [comment]
Hi,
Thanks for the suggestions! The issue that in addition to ligand-receptor interactions, we also include receptor-receptor interactions, and that's why we did not include any directionality.

**Comment by yewero** [comment]
This script could solve this problem:
https://github.com/yewero/cellphonedb/blob/7d5910a63b14c9cad71adbb952fac3e7e33b2ae6/cellphonedb/tools/orderGene.py
Unfortunately, I have no permission to upload this script here.

**Comment by yewero** [comment]
This script could simply fix the order of gene pairs in the output: https://github.com/Teichlab/cellphonedb/pull/218
