### ISSUE TITLE
cellphoneDB website not working

### ISSUE THREAD

**Issue by yjlee0331** [Teichlab/cellphonedb#177]
Hello,

I tried to use the website to explore my scRNAseq data, and it keeps giving me a 500 internal server error. Is there something wrong with the website? Are the files too big? When my files were uploading it said the total size was ~700 kb.

Thank you!

**Comment by renzorock** [comment]
Hi @yjlee0331 ... I do not think the reason is the file size. I had encountered the same error but it worked later. This time around, I have a  new error that comes up saying 'error occurred while filtering the input rows'. Have you come across this?

**Comment by mvento** [comment]
Hi @yjlee0331 @renzorock,

Server is stucked. I will unlock during this moorning.

Best

**Comment by hartmannmark** [comment]
I guess this is the case again for weeks already...

**Comment by prete** [comment]
Analysis of datasets through the website is no longer available due to the size of scRNAseq datasets. 
Please, use the python package.
