### ISSUE TITLE
Can't use my specific database

### ISSUE THREAD

**Issue by monkeyBai96** [Teichlab/cellphonedb#178]
hi, excellent work!
I have worked on cellphonedb database v2.0.0 smoothly.
But i have trouble in using my specific database.
I make interaction_file.csv include "partner_a, partner_b", and NULL column "annotation_strategy" and "source".  Fortunately it works by >cellphonedb database generate and merge my interaction with the original table.
But when i use >method statistical_analysis --database out/cellphonedb_user_2020-05-21_15.db, cellphonedb only use the original interactions, skip over my interactions.

I check the /out/interaction_input.csv and find my "user_curated" interactions.
Is there any problems with my command? Probability because the empty "annotation_strategy" and "source" columns of my_custom_interaction_file.csv.

Hope for any reply.

**Comment by mief** [comment]
Hi,
Many apologies for the late response, I hope you managed with this. The issue was that annotation_strategy and source are mandatory columns and shouldn't be empty.
