### ISSUE TITLE
[ERROR] Invalid Counts data: Some cells in meta didnt exist in counts columns. Maybe incorrect file format.

### ISSUE THREAD

**Issue by lihpsg** [Teichlab/cellphonedb#179]
I encountered this error when running cellphoneDB on the Decidua dataset. The command is as below: 

cellphonedb method statistical_analysis meta_10x.txt raw_data_10x.txt 

The set column names seems to be consistent between these two files (although not in the same order). So I wonder if there is any formatting of the input files required before running cellphoneDB?

**Comment by Daliya-K** [comment]
I also got this error, and was able to solve it by changing the format of the Counts data and the Meta data to tab separated. I also needed to switch from gene names to Ensembl IDs, even though I used the --counts-data=gene_name option.
