### ISSUE TITLE
how to get complex interacting pairs - Ensembl Id's?

### ISSUE THREAD

**Issue by franciscogrisanti** [Teichlab/cellphonedb#180]
Hi guys! 

In regards to complex interacting pairs, is there a simple way to get what ensembl id's are used in that complex?

For example, for a11b1 complex, I want to know what genes is cellphoneDB taking into consideration?

Thank you so much in advance!

Best regards,

Francisco

**Comment by EBosi** [comment]
I second that. As for now, I'm not considering complex interactions because of this, I would be extremely happy to include them in my analyses.

**Comment by mief** [comment]
Hi,
You can use the deconvoluted.txt output file (the complex_name column has the complex name for all the complexes). You can download our input files from https://www.cellphonedb.org/downloads and check the members of each complex using the complex table (with the uniprot ids) and mapping those ids to the gene table.
