### ISSUE TITLE
error installing in windows 

### ISSUE THREAD

**Issue by abappal** [Teichlab/cellphonedb#184]
Hello! Excited to run the pacakge. But get the following error at step 3 of installation.Can you please help!

(base) (cpdb-venv) C:\Users\PAI>pip install cellphonedb
Collecting cellphonedb
  Using cached https://files.pythonhosted.org/packages/e3/cc/b91d4aad0a9ed98f923e1075f87cc6a81b7b21b5472bb1cb44c3216f5a39/CellPhoneDB-2.1.3.tar.gz
Collecting click<6.7.99,>=6.7 (from cellphonedb)
  Using cached https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl
Collecting pandas<0.23.99,>=0.23 (from cellphonedb)
  Using cached https://files.pythonhosted.org/packages/58/a8/03e5fe0edbc522e46cb27df2abfb4266814129253d8462f38bc704a76a2a/pandas-0.23.4-cp37-cp37m-win_amd64.whl
Collecting flask<1.0.99,>=1.0 (from cellphonedb)
  Using cached https://files.pythonhosted.org/packages/d8/94/7350820ae209ccdba073f83220cea1c376f2621254d1e0e82609c9a65e58/Flask-1.0.4-py2.py3-none-any.whl
Collecting Flask-RESTful<0.3.99,>=0.3 (from cellphonedb)
  Using cached https://files.pythonhosted.org/packages/e9/83/d0d33c971de2d38e54b0037136c8b8d20b9c83d308bc6c220a25162755fd/Flask_RESTful-0.3.8-py2.py3-none-any.whl
Collecting Flask-Testing<0.7.99,>=0.7 (from cellphonedb)
  Using cached https://files.pythonhosted.org/packages/04/78/c8cd18b08f2f1ca3eaea56a3f2f53bc0d146f7c8faed8c64a93bc09e586a/Flask-Testing-0.7.1.tar.gz
Collecting SQLAlchemy<1.3.99,>=1.3 (from cellphonedb)
  Using cached https://files.pythonhosted.org/packages/1e/60/d0c4936f421ee8c4f9bfd310905165ad6ccea06355982cc59d3de4e55f45/SQLAlchemy-1.3.17-cp37-cp37m-win_amd64.whl
Collecting PyYAML<5.1.99,>=5.1 (from cellphonedb)
  Using cached https://files.pythonhosted.org/packages/bc/3f/4f733cd0b1b675f34beb290d465a65e0f06b492c00b111d1b75125062de1/PyYAML-5.1.2-cp37-cp37m-win_amd64.whl
Collecting requests<2.19.99,>=2.19 (from cellphonedb)
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Collecting pika<0.12.99,>=0.12 (from cellphonedb)
  Using cached https://files.pythonhosted.org/packages/bf/48/72de47f63ba353bacd74b76bb65bc63620b0706d8b0471798087cd5a4916/pika-0.12.0-py2.py3-none-any.whl
Collecting boto3<1.7.99,>=1.7 (from cellphonedb)
  Using cached https://files.pythonhosted.org/packages/ac/6e/faf7c6c3ae59641c75023fb5dcc8a02c33752ac8ccadf9931e8d8364f2fe/boto3-1.7.84-py2.py3-none-any.whl
Collecting geosketch==0.3 (from cellphonedb)
  Using cached https://files.pythonhosted.org/packages/10/dd/65931ca39a390bd2fe20f01dd07caf6d72ec34dab12156c0215c7609ab22/geosketch-0.3.tar.gz
Collecting rpy2<3.0.99,>=3.0.4 (from cellphonedb)
  Using cached https://files.pythonhosted.org/packages/c7/43/401afad8556bf92b08bd7d422cacac614b0e8dd2bce31848318bbcb18f48/rpy2-3.0.5.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\pai\cpdb-venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\PAI\\AppData\\Local\\Temp\\pip-install-foeg1jwa\\rpy2\\setup.py'"'"'; __file__='"'"'C:\\Users\\PAI\\AppData\\Local\\Temp\\pip-install-foeg1jwa\\rpy2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\PAI\AppData\Local\Temp\pip-install-foeg1jwa\rpy2\
    Complete output (89 lines):
    c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\cffi-1.14.0-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_NaN' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\cffi-1.14.0-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_NaReal' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\cffi-1.14.0-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_NaInt' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\cffi-1.14.0-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_NaString' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\cffi-1.14.0-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_BlankString' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\cffi-1.14.0-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_BlankScalarString' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\cffi-1.14.0-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_GlobalEnv' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\cffi-1.14.0-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_EmptyEnv' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\cffi-1.14.0-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_BaseEnv' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\cffi-1.14.0-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_BaseNamespace' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\cffi-1.14.0-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_BaseNamespaceRegistry' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\cffi-1.14.0-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_NilValue' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\cffi-1.14.0-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_UnboundValue' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\cffi-1.14.0-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_MissingArg' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\cffi-1.14.0-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_ClassSymbol' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\cffi-1.14.0-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_NameSymbol' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\cffi-1.14.0-py3.7-win-amd64.egg\cffi\cparser.py:164: UserWarning: Global variable 'R_DimSymbol' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    Traceback (most recent call last):
      File "c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\cffi-1.14.0-py3.7-win-amd64.egg\cffi\cparser.py", line 305, in _parse
        ast = _get_parser().parse(fullcsource)
      File "c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\pycparser-2.20-py3.7.egg\pycparser\c_parser.py", line 152, in parse
        debug=debuglevel)
      File "c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\pycparser-2.20-py3.7.egg\pycparser\ply\yacc.py", line 331, in parse
        return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
      File "c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\pycparser-2.20-py3.7.egg\pycparser\ply\yacc.py", line 1199, in parseopt_notrack
        tok = call_errorfunc(self.errorfunc, errtoken, self)
      File "c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\pycparser-2.20-py3.7.egg\pycparser\ply\yacc.py", line 193, in call_errorfunc
        r = errorfunc(token)
      File "c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\pycparser-2.20-py3.7.egg\pycparser\c_parser.py", line 1861, in p_error
        column=self.clex.find_tok_column(p)))
      File "c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\pycparser-2.20-py3.7.egg\pycparser\plyparser.py", line 67, in _parse_error
        raise ParseError("%s: %s" % (coord, msg))
    pycparser.plyparser.ParseError: <cdef source string>:23:5: before: blah1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\PAI\AppData\Local\Temp\pip-install-foeg1jwa\rpy2\setup.py", line 184, in <module>
        'rpy2': ['doc/source/rpy2_logo.png', ]}
      File "c:\users\pai\cpdb-venv\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\PAI\anaconda3\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\users\pai\cpdb-venv\lib\site-packages\setuptools\dist.py", line 446, in __init__
        k: v for k, v in attrs.items()
      File "C:\Users\PAI\anaconda3\lib\distutils\dist.py", line 292, in __init__
        self.finalize_options()
      File "c:\users\pai\cpdb-venv\lib\site-packages\setuptools\dist.py", line 734, in finalize_options
        ep.load()(self, ep.name, value)
      File "c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\cffi-1.14.0-py3.7-win-amd64.egg\cffi\setuptools_ext.py", line 217, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\cffi-1.14.0-py3.7-win-amd64.egg\cffi\setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\cffi-1.14.0-py3.7-win-amd64.egg\cffi\setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "rpy/_rinterface_cffi_build.py", line 546, in <module>
        """ if os.name == 'nt' else ''
      File "c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\cffi-1.14.0-py3.7-win-amd64.egg\cffi\api.py", line 112, in cdef
        self._cdef(csource, override=override, packed=packed, pack=pack)
      File "c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\cffi-1.14.0-py3.7-win-amd64.egg\cffi\api.py", line 126, in _cdef
        self._parser.parse(csource, override=override, **options)
      File "c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\cffi-1.14.0-py3.7-win-amd64.egg\cffi\cparser.py", line 358, in parse
        self._internal_parse(csource)
      File "c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\cffi-1.14.0-py3.7-win-amd64.egg\cffi\cparser.py", line 363, in _internal_parse
        ast, macros, csource = self._parse(csource)
      File "c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\cffi-1.14.0-py3.7-win-amd64.egg\cffi\cparser.py", line 307, in _parse
        self.convert_pycparser_error(e, csource)
      File "c:\users\pai\appdata\local\temp\pip-install-foeg1jwa\rpy2\.eggs\cffi-1.14.0-py3.7-win-amd64.egg\cffi\cparser.py", line 336, in convert_pycparser_error
        raise CDefError(msg)
    cffi.CDefError: cannot parse "blah1 ReadConsole;"
    <cdef source string>:23:5: before: blah1
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by MedicalKong** [comment]
I met the same error. Looking forward to the reply from developers.

**Comment by XiaofeiSunUCSF** [comment]
Using cached rpy2-3.0.5.tar.gz (117 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\xsun4\venv\Scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xsun4\\AppData\\Local\\Temp\\1\\pip-install-p7v72d4x\\rpy2\\setup.py'"'"'; __file__='"'"'C:\\Users\\xsun4\\AppData\\Local\\Temp\\1\\pip-install-p7v72d4x\\rpy2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\xsun4\AppData\Local\Temp\1\pip-pip-egg-info-3bpnhj6s'
         cwd: C:\Users\xsun4\AppData\Local\Temp\1\pip-install-p7v72d4x\rpy2\
    Complete output (91 lines):
    d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\cffi\cparser.py:164: UserWarning: Global variable 'R_NaN' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\cffi\cparser.py:164: UserWarning: Global variable 'R_NaReal' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\cffi\cparser.py:164: UserWarning: Global variable 'R_NaInt' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\cffi\cparser.py:164: UserWarning: Global variable 'R_NaString' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\cffi\cparser.py:164: UserWarning: Global variable 'R_BlankString' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\cffi\cparser.py:164: UserWarning: Global variable 'R_BlankScalarString' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\cffi\cparser.py:164: UserWarning: Global variable 'R_GlobalEnv' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\cffi\cparser.py:164: UserWarning: Global variable 'R_EmptyEnv' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\cffi\cparser.py:164: UserWarning: Global variable 'R_BaseEnv' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\cffi\cparser.py:164: UserWarning: Global variable 'R_BaseNamespace' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\cffi\cparser.py:164: UserWarning: Global variable 'R_BaseNamespaceRegistry' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\cffi\cparser.py:164: UserWarning: Global variable 'R_NilValue' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\cffi\cparser.py:164: UserWarning: Global variable 'R_UnboundValue' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\cffi\cparser.py:164: UserWarning: Global variable 'R_MissingArg' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\cffi\cparser.py:164: UserWarning: Global variable 'R_ClassSymbol' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\cffi\cparser.py:164: UserWarning: Global variable 'R_NameSymbol' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\cffi\cparser.py:164: UserWarning: Global variable 'R_DimSymbol' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    Traceback (most recent call last):
      File "d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\cffi\cparser.py", line 305, in _parse
        ast = _get_parser().parse(fullcsource)
      File "d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\pycparser\c_parser.py", line 152, in parse
        debug=debuglevel)
      File "d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\pycparser\ply\yacc.py", line 331, in parse
        return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
      File "d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\pycparser\ply\yacc.py", line 1199, in parseopt_notrack
        tok = call_errorfunc(self.errorfunc, errtoken, self)
      File "d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\pycparser\ply\yacc.py", line 193, in call_errorfunc
        r = errorfunc(token)
      File "d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\pycparser\c_parser.py", line 1861, in p_error
        column=self.clex.find_tok_column(p)))
      File "d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\pycparser\plyparser.py", line 67, in _parse_error
        raise ParseError("%s: %s" % (coord, msg))
    pycparser.plyparser.ParseError: <cdef source string>:23:5: before: blah1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\xsun4\AppData\Local\Temp\1\pip-install-p7v72d4x\rpy2\setup.py", line 184, in <module>
        'rpy2': ['doc/source/rpy2_logo.png', ]}
      File "C:\Users\xsun4\venv\lib\site-packages\setuptools\__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "d:\users\xsun4\anaconda3\envs\rstudio\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:\Users\xsun4\venv\lib\site-packages\setuptools\dist.py", line 430, in __init__
        k: v for k, v in attrs.items()
      File "d:\users\xsun4\anaconda3\envs\rstudio\lib\distutils\dist.py", line 281, in __init__
        self.finalize_options()
      File "C:\Users\xsun4\venv\lib\site-packages\setuptools\dist.py", line 721, in finalize_options
        ep(self)
      File "C:\Users\xsun4\venv\lib\site-packages\setuptools\dist.py", line 728, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\cffi\setuptools_ext.py", line 217, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\cffi\setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\cffi\setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "rpy/_rinterface_cffi_build.py", line 546, in <module>
        """ if os.name == 'nt' else ''
      File "d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\cffi\api.py", line 112, in cdef
        self._cdef(csource, override=override, packed=packed, pack=pack)
      File "d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\cffi\api.py", line 126, in _cdef
        self._parser.parse(csource, override=override, **options)
      File "d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\cffi\cparser.py", line 358, in parse
        self._internal_parse(csource)
      File "d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\cffi\cparser.py", line 363, in _internal_parse
        ast, macros, csource = self._parse(csource)
      File "d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\cffi\cparser.py", line 307, in _parse
        self.convert_pycparser_error(e, csource)
      File "d:\users\xsun4\anaconda3\envs\rstudio\lib\site-packages\cffi\cparser.py", line 336, in convert_pycparser_error
        raise CDefError(msg)
    cffi.CDefError: cannot parse "blah1 ReadConsole;"
    <cdef source string>:23:5: before: blah1
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by moutazhelal** [comment]
Hello @abappal I am facing the same error did you manage to fix it ?

**Comment by xihuiyin** [comment]
Hello, I am having the same issue as well. Hoping someone has any input on what went wrong.

**Comment by JohnWang1997** [comment]
Try this 'https://mp.weixin.qq.com/s/0PfA0bqdvrEbo62zPVq4kQ' which gives a damo for using linux in Windows10 system.

**Comment by mief** [comment]
CellPhoneDB works on MAC OS and Linux, it doesn't work on Windows unfortunately.
