### ISSUE TITLE
Is there a example of your_custom_interaction_file.csv?

### ISSUE THREAD

**Issue by nkm47** [Teichlab/cellphonedb#185]
Hi，
    When i want to Generate user-specific custom database, I just find some example like user_complex.csv. I can not find the example file of your_custom_interaction_file.csv. Is there a format of your_custom_interaction_file.csv?
    Thanks a lot!

**Comment by mief** [comment]
Hi, 
Apologies for the late response. You can use our files on https://www.cellphonedb.org/downloads as example files for creating a custom database. For custom_interactions, you can use the Interaction input file.
