### ISSUE TITLE
normal mode vs statistical analysis mode

### ISSUE THREAD

**Issue by yanwengong** [Teichlab/cellphonedb#186]
I have tried both "cellphonedb method statistical_analysis" and "cellphonedb method analysis" (normal mode). Couple questions:
1. Compared with statistical_analysis, the normal mode does not perform the perturbation and p-value calculation, but everything else should be the same, which lead to the same means.txt?
2. How does the significant_means.txt generated in the normal mode which does not compute p-value?

Another general question is, how to interpret that both geneA and geneB can be receptors in the means.txt?

Thank you!

**Comment by mief** [comment]
Hi,
Apologies for the late response. Yes, that's true, the normal mode does not use the perturbations. The significant means file would be the means of all that passed the specific threshold. 
In addition to ligand-receptor interactions, we also included receptor-receptor interactions in our database.
I hope this helps,
Mirjana

**Comment by MingwuDuan** [comment]
> Hi,
> Apologies for the late response. Yes, that's true, the normal mode does not use the perturbations. The significant means file would be the means of all that passed the specific threshold.
> In addition to ligand-receptor interactions, we also included receptor-receptor interactions in our database.
> I hope this helps,
> Mirjana

The word 'specific threshold' you refered to means '--threshold: % of cells expressing the specific ligand/receptor' at rep homepage? But it doesn't have default value.
