### ISSUE TITLE
Number of interactions in count_network.tsv

### ISSUE THREAD

**Issue by TobiTekath** [Teichlab/cellphonedb#187]
Hi,

I just noticed that when plotting the heatmap the number of interactions in the "count_network.tsv" ("--count-network-name") are not correct, as the (significant) interactions of A -> B and B -> A are summed together beforehand (if A and B are different cell types). 

Or is there a specific reasoning for this behaviour?

The same goes for the actual plot, which explains the perfect symmetry of the plot.

**Comment by panxiaoguang** [comment]
you can see here https://github.com/Teichlab/cellphonedb/blob/master/Docs/RESULTS-DOCUMENTATION.md

**Comment by TobiTekath** [comment]
Thanks @panxiaoguang  for the link, but what I meant to point out is that it is counter intuitive to write out a table of the number of interactions which separate entries for A -> B and B -> A, but both having the same number because they both represent A <-> B.

I hope that made my point more clear.
Thanks.
