### ISSUE TITLE
CellPhoneDB website overloaded

### ISSUE THREAD

**Issue by ssch313** [Teichlab/cellphonedb#188]
Hello :)
Thanks for this helpful tool!
I see a notification on the CellPhoneDB website saying that the processing server is overloaded and one should try later. Unfortunately this is the case since two weeks throughout the whole day (I check it regularly and at different time points). So I was wondering if it's maybe a problem with my computer or with the server and if you know when the tool will be available again? I have no idea about how to use Python (only R) so it would be great if I could use the website :)
Thank you very much!

**Comment by HeyLifeHD** [comment]
Installing an older scikit-learn version worked for me!
```
pip uninstall scikit-learn
pip install scikit-learn==0.22
```
