### ISSUE TITLE
How to use cellphoneDB

### ISSUE THREAD

**Issue by rachel662** [Teichlab/cellphonedb#189]
Hi, 
I'm new to single-cell RNA seq and was wondering if anyone could explain a bit more about the basics of using CellphoneDB, 
the instructions seem to be good for the terminal? But how might one run it in R or Python? 

Thanks! 
Rachel

**Comment by mief** [comment]
Hi,
The method only works with the terminal for now. We haven't implemented an API yet, but perhaps in future. 
Thanks,
Mirjana
