### ISSUE TITLE
p-values of 0.0

### ISSUE THREAD

**Issue by HichamAffia** [Teichlab/cellphonedb#19]

**Comment by HichamAffia** [comment]
Hi, I'm running CellPhoneDB with a  --result-precision of 10 and I get a lot of straight 0.0 in the p-values output.

I wonder if I should consider them as p<0.0000000001 or if there is another way to look at it. 

Like in the Fig5 a of the **Single-cell reconstruction of the early maternal–fetal interface in humans** paper of  would like plot the results for some clusters and to adjust the size of my dots according to the pvalue, so p-values of zero are a little problematic for me.

Thank you!

**Comment by mief** [comment]
Hi,
Yes, that's also what we did to produce the dot plot, we replaced all zeros with very small numbers and then wrote >= certain -log10(p-value) in the legend.
Best,
Mirjana

**Comment by rcw1** [comment]
I am having the same issue. I am using a single cell dataset with ~20k cells, running with the default 1000 permutations, and my p-values with CellPhoneDB are either 0.0 or 1.0. There are a few p-values that are in between, but not many. Is this what one should expect?

**Comment by mief** [comment]
Hi,
Please uninstall and then install the new version. --result-precision is now by default 3.
