### ISSUE TITLE
Error: no such option: --counts-data

### ISSUE THREAD

**Issue by KhushiVirah** [Teichlab/cellphonedb#190]
Hi,

I'm having some issues with one of the optional parameter: --counts-data . Might there be another parameter that i could use? Because when i'm removing this parameter i'm getting another error since my data are that of mice : [ERROR] All counts filtered: Are you using human data?.

**Comment by mief** [comment]
CellPhoneDB works only with human data, if you want to use it with mouse data you can use orthologs (you would need to convert your mouse genes into their human orthologs)
