### ISSUE TITLE
question for results file

### ISSUE THREAD

**Issue by MMriran** [Teichlab/cellphonedb#192]
Hi, Thank you for your great tools！ I had a question for results files. What is  the  numerical value means in "means.txt"?（means.txt） Thank you!

**Comment by Daliya-K** [comment]
According to the documentation: the mean values in the "means.txt" output  refers to the total mean of the individual partner average expression values in the corresponding interacting pairs of cell types. If one of the mean values is 0, then the total mean is set to 0.

**Comment by MMriran** [comment]
Thank you for your reply.  So is the numerical value  in  "means.txt" stand for the strength of interactions between cells?  And what files （means.txt? or significant means.txt） should I used to draw a cell-cell communications？

**Comment by mief** [comment]
Hi,
The means file shows the mean of the average receptor and average ligand expression level in the corresponding clusters. Or if you have a column X|Y for a specific interaction R1-L1, then the mean would be mean(mean(R1 in cluster X), mean(L1 in cluster Y)). The significant means table shows the means of only the significant interactions, and all others are set to 0. If you want to draw the significant interactions, you should use the significant means file.
