### ISSUE TITLE
How accurate is the human database analysis of mouse data？

### ISSUE THREAD

**Issue by skydashan** [Teichlab/cellphonedb#194]
Hi：
        I found no mouse  in the database，if I use human database instead of mouse，how accurate is the human database analysis of mouse data？

Thanks！！！

**Comment by mief** [comment]
Hi,
That is true, our database has been manually curated only considering human interactions. For mouse datasets, we have used orthologs. We have used it successfully in this way, but we can't guarantee about the accuracy of all interactions, we have not have the time to manually curate mouse interactions. We welcome any input from users, if they have curated interactions, it would be quite easy for us to include them in the database.
Thanks,
Mirjana
