### ISSUE TITLE
Null distribution

### ISSUE THREAD

**Issue by huangyh09** [Teichlab/cellphonedb#196]
Hi,

Thanks for developing this nice tool. I just want to ask that when generating the Null distribution, the Nat Prot paper says that all cells are (equally) permutated. Will this generate a null distribution biased towards the major cell type, e.g., CD4 in PBMC? I saw a subsampling strategy is introduced, but why not subsampling equal number of cells per cell type.

Also, it only tests if a ligand-receptor interaction is enriched on a cluster pair, comparing to the any-pair background. Therefore, if a ligand-receptor interaction is universal, i.e., for all cluster pairs. None of them will be significant. Is my understanding correct?

Thanks,
Yuanhua

**Comment by mief** [comment]
Hi,
Thanks for the comments! Yes, this is true, there might be a bias towards major cell types, and this would make it a bit easier for small cell types to get significant results. The issue with subsampling equal number of cells is that often we have very small clusters. If this is possible for your specific dataset, you could definitely try this.
The comparison of each cluster pair is not with any pair background, it's with the random mean of the same pair background (or how would the mean look like if there were random clusters).
I hope this helps,
Mirjana
