### ISSUE TITLE
Q: Calculation of mean values of interacting partners when partner is complex AND members' minimum value is zero

### ISSUE THREAD

**Issue by mjgomezv** [Teichlab/cellphonedb#197]
Hi, 

I understand from the publication that when one of the interacting partners is a complex, the '_member of the complex with the minimum average expression is considered for the subsequent statistical analysis_'. 

However, is this the case when the members' minimum average expression in a complex is zero? Seems like in such cases, cellphoneDB takes the other member's value. Is this correct? I would expect that in these cases, everything is set to zero, like it happens when the interacting partners are not complexes. 

Many thanks, 
Maria

**Comment by mief** [comment]
Hi,

Apologies for the delay with the answer. The first check we are doing is checking if all members of the complex have higher expression than 0, so if any of them is 0, the interactions with this complex are automatically put as not significant, with a p-value of 1.

Best,
Mirjana
