### ISSUE TITLE
Filtering the results and visualization

### ISSUE THREAD

**Issue by hkarakurt8742** [Teichlab/cellphonedb#20]
Hello,
I used CellPhoneDB for my data and I want to visualize it in Cytoscape. I prepared a proper network file but it is too big to have a proper visualization. I used significant_means file as the significant results and used it. Network has 29 nodes and 12310 edges and the node with the lowest degree has 258 degrees. How can I filter these results? I've seen in the publication you said "edges with more than 30 interactions" so basically you removed the interacting pairs below 30?
I have looked for documentation for results but could not find any information about this value. What does it represent actually?

Thank you in advance

**Comment by mief** [comment]
Hello,
In our case, the nodes in the networks represented cell types and the edges  - the number of significant interactions between two cell types. The network for the decidua had many edges and for better visualisation, we decided to filter edges with less than 30 interactions. That worked best for us, but it depends on the specific network that you have. In the placenta for example, we didn't need to filter at all. 
We didn't want to filter nodes, so we didn't use the node degree.
Best,
Mirjana

**Comment by hkarakurt8742** [comment]
> Hello,
> In our case, the nodes in the networks represented cell types and the edges - the number of significant interactions between two cell types. The network for the decidua had many edges and for better visualisation, we decided to filter edges with less than 30 interactions. That worked best for us, but it depends on the specific network that you have. In the placenta for example, we didn't need to filter at all.
> We didn't want to filter nodes, so we didn't use the node degree.
> Best,
> Mirjana

Thank you Mirjana for your answer.
The thing I have doubt is; in the network edges are interactions between cell types but how can an edge have a degree as you mentioned in article? Degree is a property of node as I know.
Did you mean, if 2 cell types have interactions less than 30, you ignored those interactions?

Thank you again.

**Comment by mief** [comment]
Hi,
Yes, exactly, if 2 cell types have interactions less than 30, we removed them from the network. 
We never mentioned anything about degree, in the manuscript is written:
The decidual network was created considering only edges with more than 30 interactions.
Best,
Mirjana

**Comment by DHGK** [comment]
I'm new to the network visualization, would you mind let me know how to convert cellphoneDB outputs (pvalues/significant_means) to a sif file taken by the Cytoscape?

**Comment by Mohebg1234** [comment]
@DHGK , I have the same question.
@mief can you please let us know how to import cellphone output into cytoscape ?

**Comment by rachel662** [comment]
Hi there, 
I'd definitely be interested in using cytoscape to visualise my results too, would you be able to share? 
Thanks so much
