### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by hemadelon** [Teichlab/cellphonedb#202]
Hi guys,

Great package!
I'm working on a Mac, with Anaconda v 2020.07, python 3.8.3. and pip 20.1.1
I'm unable to install the package via pip due to PyYAML that cannot be uninstalled.

`Attempting uninstall: PyYAML
Found existing installation: PyYAML 5.3.1.
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall. `

This apparently is an issue that affects multiple installations of libraries, yet I haven't come across a solution. 
I've read that it's an issue with newer pip versions, and that downgrading may help, but I'm finding that it doesn't (for me).

Has anyone here run into this issue and had another solution?

Best,
Madelon

**Comment by HaojiaWu** [comment]
you can try: pip install --ignore-installed cellphonedb
