### ISSUE TITLE
Issue with Invalid Counts Data

### ISSUE THREAD

**Issue by SaskiaFreytag** [Teichlab/cellphonedb#203]
Hi,

I have been trying to run CellPhoneDB on my own data but kept getting Invalid Counts Error. I then switched to your test data and obtained the same data. I have even installed it in an environment as suggested but it would not change the result.

Any help would be much appreciated!

**Comment by mief** [comment]
Hi,
Can you send us a sample of your input data and we can try to test it?
Thanks!

**Comment by wuzhigui** [comment]
Counts values are not decimal values
![image](https://user-images.githubusercontent.com/70992194/110454163-e0b76d80-8101-11eb-8777-476b9398fc74.png)
Who can help me !  please !

**Comment by prete** [comment]
Hi @wuzhigui can you provide a sample of your input data that we can use to reproduce your error?

**Comment by wuzhigui** [comment]
thanks , i have solved this error.



---Original---
From: ***@***.***&gt;
Date: Fri, May 7, 2021 20:25 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Teichlab/cellphonedb] Issue with Invalid Counts Data (#203)




 
@wuzhigui your counts file probably had the wrong format. Were you able to run your analysis?

**Comment by prete** [comment]
@SaskiaFreytag this is probably too late, but did you too manage to run your analysis?

**Comment by wuzhigui** [comment]
yes



---Original---
From: ***@***.***&gt;
Date: Fri, May 7, 2021 20:32 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Teichlab/cellphonedb] Issue with Invalid Counts Data (#203)




 
@SaskiaFreytag this is probably too late, but did you too manage to run your analysis?

**Comment by prete** [comment]
> yes

Thanks wuzhigui, but I was asking the original reporter of the issue (@SaskiaFreytag) that second time. I'll give them some time to check-in and then I'll close the issue.

**Comment by monikaramos** [comment]
Hi. I am having this same error. Can someone provide an explanation?

**Comment by xiaoxiaofuyou** [comment]
Oh, who can help me to solve this problem,  i got the same error, thank you!

![image](https://user-images.githubusercontent.com/105490459/175263857-9707fa74-650e-424a-85ad-33a40287029b.png)

Best to all of you.

**Comment by Portulaca666** [comment]
It is very&nbsp;explicit that you should use Symbol gene type .

---Original---
From: ***@***.***&gt;
Date: Thu, Jun 23, 2022 17:16 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Teichlab/cellphonedb] Issue with Invalid Counts Data (#203)




 
Oh, who can help me to solve this problem,  i got the same error, thank you!
 

 
Best to all of you.

**Comment by xiaoxiaofuyou** [comment]
> 

Yes, i used Symbol gene type, but it seems not working

**Comment by prete** [comment]
Hi @xiaoxiaofuyou as wuzigui mentioned there's a WARNING with a pretty explicit message. It says that your data is not using enembl gene names. You should run your command with  the option `--counts-data hgnc_symbol` if you're using gene names instead of ensembl gene identifiers.

Should that not work you may want to have a second look at the format of your data. Are they valid tab or comma separated values? Perhaps you can provide the files you're trying to use so we can give you better guidance.

**Comment by xiaoxiaofuyou** [comment]
Thank you. I solved it by adding a code. 
**mycounts <-  as.matrix(mycounts)**
