### ISSUE TITLE
pval[pval==0] = 0.0009 (plot_dot_by_column_name.R)

### ISSUE THREAD

**Issue by peerkarmaus** [Teichlab/cellphonedb#206]
In the plotting function _plot_dot_by_column_name.R_, Line 34 reads `pval[pval==0] = 0.0009` 

Is there a floating point issue in the python code or why are zeros converted to what seems like an arbitrary "0.0009" value? Many of my results are `pval==0`, so I am worried this could be an issue introduced by limited floating points.

Can someone comment on this?

**Comment by mief** [comment]
Yes, the zeros are converted to a small arbitrary value.
