### ISSUE TITLE
How to use cellphonedb to annotate genes with interactions?

### ISSUE THREAD

**Issue by racng** [Teichlab/cellphonedb#207]
Is it possible to use cellphonedb as a python package in python scripts to query interactions without performing single cell specific analysis and without using the command line interface? Something like how we can search up gene names on the cellphonedb.org website to get the partner gene names and interaction ID?

**Comment by mief** [comment]
That hasn't been implemented yet, apologies. But it's a good idea and we'll see if we can included it future. For now, the best would be to download our input files from https://www.cellphonedb.org/downloads.
