### ISSUE TITLE
Issue with running the code

### ISSUE THREAD

**Issue by dianadom** [Teichlab/cellphonedb#222]
Hi,
I am running a code on a big files. Files with counts have 7GB. 

The command which I am running is following:
cellphonedb method statistical_analysis  metadata.txt counts.txt --iterations=10 --project-name=new

This is a 'head' of metadata file:

Cell	cell_type
N7.EpiA.AAACATACACACTG	TA_1
N7.EpiA.AAACCGTGCATCAG	TA_1
N7.EpiA.AAACGCACAATCGC	TA_2
N7.EpiA.AAAGATCTAACCGT	Enterocyte_Progenitors
N7.EpiA.AAAGATCTAGGCGA	Enterocyte_Progenitors
....

and this is a 'head' of counts file:
Gene	N7.EpiA.AAACATACACACTG	N7.EpiA.AAACCGTGCATCAG	N7.EpiA.AAACGCACAATCGC	N7.EpiA.AAAGATCTAACCGT	N7.EpiA.AAAGATCTAGGCGN7.EpiA.AAAGCCTGCTCGAA	N7.EpiA.AAATCAACATCACG	N7.EpiA.AAATCAACCTTGGA	N7.EpiA.AAATCATGGAAAGT	N7.EpiA.AAATCCCTCACTTT	N7.EpiA.AACAAACTGTATGC	N7.EpiA.AACAAACTTCTCCG	.....
7SK	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0.592989170245371	0	0	0	0	0	0	0	0	0	0	0	0	0	1.80225274494389	0	0	0	0	0	0	0	0	0	0	0	0	0	0	1.67952384541575	0	0	0	0	0	0	0	0	0	0	0	0	0	0	3.08145210306442	0	0.....
A1BG	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	2.2072425502065	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0.690259738916243	0	0	0	0	0	0	0	0	0	0	0	0	0	0.738263600026138	0	0	0	0	0	0	0	0	0	0	0	0	0	0.519176176574229	0	0	0	0	0	0	0	0	0	0	0	0	0	0.481101840353243	0	0	0	0	0	0	0	0	0	0	0	0	0	0.651909543708293	0	0......
....

After running the command I am getting the following information:
[ ][APP][13/11/20-09:46:24][WARNING] Latest local available version is `v2.0.0`, using it
[ ][APP][13/11/20-09:46:24][WARNING] User selected downloaded database `v2.0.0` is available, using it
[ ][CORE][13/11/20-09:46:24][INFO] Initializing SqlAlchemy CellPhoneDB Core
[ ][CORE][13/11/20-09:46:24][INFO] Using custom database at /cluster/home/dianadom/.cpdb/releases/v2.0.0/cellphone.db
[ ][APP][13/11/20-09:46:24][INFO] Launching Method cpdb_statistical_analysis_local_method_launcher
[ ][APP][13/11/20-09:46:24][INFO] Launching Method _set_paths
[ ][APP][13/11/20-09:46:24][INFO] Launching Method _load_meta_counts

After it the job is not running anymore ( no information that it has been killed) and I am not getting any output.

**Comment by edwardkim1** [comment]
I have the same issue here using the test data. The job does not run after "Launching Method _counts_validations" and Ctrl+C is unable to kill it either.

**Comment by madelarambelje** [comment]
I am having this problem as well, can this be caused due to the lack of computational power or memory?

**Comment by prete** [comment]
Hi @dianadom @edwardkim1 @madelarambelje this sounds like it could be a memory issue. Could you try upgrading to the **beta version** of CellPhoneDB (`pip install -U CellPhoneDB==2.1.8b3`) and see if you're still facing this issue?

Similar to #282

**Comment by madelarambelje** [comment]
It was indeed a memory issue. It's running smoothly now. Thanks for responding!
