### ISSUE TITLE
Incompatible with Python 3.5

### ISSUE THREAD

**Issue by levlitichev** [Teichlab/cellphonedb#224]
Hello,

I'm in the process of getting CellPhoneDb up and running. I attempted to use Python 3.5 with CellPhoneDb and received the following error message:

```
File "/Users/lev/miniconda2/envs/cellphonedb/lib/python3.5/site-packages/cellphonedb/src/core/database/sqlalchemy_repository/InteractionRepository.py", line 48
    multidata_expanded: pd.DataFrame = self.database_manager.get_repository('multidata').get_all_expanded(
                      ^
SyntaxError: invalid syntax
```

As the error message indicates, it looks like the syntax in [this line of code](
https://github.com/Teichlab/cellphonedb/blob/b8cdfa0e847e62427f019547a30b00ee5b8e7fc0/cellphonedb/src/core/database/sqlalchemy_repository/InteractionRepository.py#L48) wasn't supported prior to Python 3.6. The problem went away when I used Python 3.6.

Might be worth updating the README to say that CellPhoneDb requires Python 3.6 and up, not Python 3.5.

Best regards,
Lev

**Comment by prete** [comment]
Python 3.6 marked as minimum requirement for CellPhoneDB after #264 (v2.1.6)
