### ISSUE TITLE
Coding error in line 48 of cellphonedb/src/core/database/sqlalchemy_repository/InteractionRepository.py

### ISSUE THREAD

**Issue by cartof** [Teichlab/cellphonedb#226]
Coding error in line 48 of cellphonedb/src/core/database/sqlalchemy_repository/InteractionRepository.py

Might have been a copy/paste error when coding or something like that. This is the wrong code:

`multidata_expanded: pd.DataFrame = self.database_manager.get_repository('multidata').get_all_expanded(
            include_gene)`

By removing `: pd.DataFrame` it's fixed.

**Comment by prete** [comment]
@cartof thanks for pointing that out. It may look a bit out of place, but it's not really an error as it's supported by [PEP-526](https://www.python.org/dev/peps/pep-0526/).
