### ISSUE TITLE
Designation of clusters that express ligand vs. receptor

### ISSUE THREAD

**Issue by 14lwt1** [Teichlab/cellphonedb#228]
Hi,

I have a naïve question regarding the workflow of CellphoneDB.
From the web portal, it is stated that "the mean of the average receptor expression level in a cluster and the average ligand expression level in the interacting cluster" is used for permutation. But how does the algorithm decide whether a cluster secretes ligands or expresses receptors? (https://www.cellphonedb.org/explore-sc-rna-seq)
![image](https://user-images.githubusercontent.com/59578221/100037994-0cfbe800-2db8-11eb-9220-af0c01c3ef09.png)
Isn't it possible for a cluster to express both the ligand and receptor?

Thanks
Henry

**Comment by luzgaral** [comment]
Hi Henry,

CellphoneDB test all possible combinations, therefore all clusters can express the ligand and/or the receptor.
For example, when testing if cellA can communicate to cellB, cellphoneDB will test `R1-cellA ::: L1-cellB` and viceversa `R1-cellB ::: L1-cellA`. 

Hope this makes sense.

Luz
