### ISSUE TITLE
Minimum number of cells in a cluster

### ISSUE THREAD

**Issue by sobjb7osx2** [Teichlab/cellphonedb#23]
Hi. I appreciate this great tool that you have developed.
I understand that the threshold can be set to only take into account ligand-receptor interactions if they are expressed in set % of cells. 
I was wondering what is the minimum (if at all) number of cells in a cluster for an enriched ligand-receptor pairs to be meaningful? Hypothetically, if a cluster has 5 cells, would an enriched ligand-receptor pair concerning that cluster be valid at all? What cell number in a cluster would you consider acceptable to add confidence to a validity of the results? Thank you very much!

**Comment by mief** [comment]
Hi,
Thank you very much for your interest in our tool.
This depends on how confident you are that the specific cell type really exists. We have used the method successfully with datasets with cell types with 5 cells, and we got biologically relevant results. If it is a very rare cell type, perhaps experimental methods for validating it could be used, for example smFISH. 
Best,
Mirjana
