### ISSUE TITLE
Unexpected interaction HLADPB1-NRG1 (also not found in the cited source database)

### ISSUE THREAD

**Issue by MaxKman** [Teichlab/cellphonedb#233]
Dear cellphonedb team,

thanks for providing and maintaining such a great resource. In one of the analysis I performed with cellphonedb the following interaction came up:
HLADPB1 - NRG1

I found this interaction surprising (from a biological point of view) so I tried to look it up in the literature but couldn't find anything. In cellphonedb the source for this interaction is noted as 'InnateDB-All'. However, I also couldn't find this interaction listed at https://www.innatedb.com/

Can you still trace where it came from? I thought I bring this up in case there is a systematic problem causing this (and potentially other false entries). Of course it might just come from an older version of innatedb.

Thanks!

Best,
Max

**Comment by MaxKman** [comment]
Hey again,

After looking a bit further here are some more examples of HLA interactions which seem to have the same problem:
HLA-C - FAM3C (CPI-SS034D36D2F)
HLADQB2 - PRL (CPI-SS026776C89)
HLADPA1 - TNFL9 (CPI-SS028784FC6)

would be good to now what is going on there, also because these interactions make there way into the literature (e.g. HLA-C/FAM3c in https://www.nature.com/articles/s41467-020-16164-1.pdf?origin=ppub). 

I hope it's just some misunderstanding on my side!

Best,
Max

**Comment by rvento** [comment]
Dear Max,

Thank you for pointing this out.  The interaction is available at https://psicquic.all.innatedb.com/webservices/current/search/query/species:human  . Still, we strongly encourage our users to rather use the curated interactions. 

Best,

Roser
