### ISSUE TITLE
output gene name format

### ISSUE THREAD

**Issue by justinesjw** [Teichlab/cellphonedb#24]
Hi! 

Awesome software! Thank you!

I was wondering what is the format of the output gene name. I noticed that some are gene symbols some are not (i.e. FcRn complex)

**Comment by mief** [comment]
Hi,

Thanks for your interest in our tool!

Some of the receptors/ligands are complexes composed of multiple subunits. For those, you can take a look at the deconvoluted.txt output file where you can find all the genes of the subunits that participate in a certain complex. This information can also be found in the complex input file that can be downloaded on our https://www.cellphonedb.org, in the Downloads section.

Best,
Mirjana
