### ISSUE TITLE
problems about install 

### ISSUE THREAD

**Issue by wuzhigui** [Teichlab/cellphonedb#240]
Sorry to borther you ! I had one question about install . Well , my  python's version is 3.7 , and  I had set up a new conda enviroment with `conda create -n cellphoneDB  python=3.7` . When i run the pipeline in github ,I got the following error .
 ![image](https://user-images.githubusercontent.com/70992194/101269880-597af680-37ae-11eb-9928-ac6aec39dadd.png)
Then I did my best to `conda install sklearn` , but I found that is not easy .
![image](https://user-images.githubusercontent.com/70992194/101269981-44529780-37af-11eb-8b63-614313654716.png)
Do someone got the same error with me ?Who can help me ,please !

**Comment by prete** [comment]
Hi, CellphoneDB is using a deprected sklearn API compared to the one conda is trying to install. Please, first install the exact  `sklearn` version required using:
 `pip install scikit-learn==0.22` 
or 
`conda install scikit-learn==0.22`

_Side note: The name of the package is `scikit-learn`, but it is imported as `sklearn`. That sometimes leads to confusions._

**Comment by HeyLifeHD** [comment]
Fixing the scikit-learn version has also worked for me!
```
pip uninstall scikit-learn
pip install scikit-learn==0.22
```
