### ISSUE TITLE
Do you have to normalise your counts before running cellphoneDB?

### ISSUE THREAD

**Issue by rachel662** [Teichlab/cellphonedb#241]
Hi there, 

this might be a silly question, but do you have to normalise the counts file from scRNA-seq before running cellphoneDB?
and then just saved the normalised counts file as a txt file? 

thanks so much 
Rachel

**Comment by yewero** [comment]
It is recommended to use normalized count data. (https://www.cellphonedb.org/faq-and-troubleshooting)
