### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by YinCY123** [Teichlab/cellphonedb#248]
can not install cellphonedb in python virsual environment, in the step of install pandas, python version 3.8.0

**Comment by Adina-ballaban** [comment]
I had the same issue. Installing using python version 3.7.9 worked for me.

**Comment by prete** [comment]
Hi @YinCY123 for the time being CellphoneDB only seems to work only with python version from 3.5.0 to 3.7.9. This has been address in issues #183 and #237. 

Your options are:
- Change your python version or create a new environment with a compatible python version (ie: `conda create -n cpdb python=3.7`).
- Use it from a container, you can pull CellphoneDB's image from [Singularity Library](https://cloud.sylabs.io/library/cellphonedb/default/cellphonedb) or [Docker quay.io registry](https://quay.io/repository/cellphonedb/cellphonedb) and run it as a container.
