### ISSUE TITLE
Can't activate the virtual environment in Windows 10 

### ISSUE THREAD

**Issue by rachel662** [Teichlab/cellphonedb#252]
Hi there, 
I was trying to activate the virtual environment in windows 10, however the line given in the readme to activate it doesn't work for me 

I get the error 
'source' is not recognized as an internal or external command,
operable program or batch file.

would anyone be able to help me solve this? 
thanks so much, Rachel

**Comment by prete** [comment]
Hi @rachel662 , `source` is a shell command for POSIX (Linux/Mac) environments. 
On Windows, virtualenv creates a special file for you to activete the environment, you should run `\path\to\cpdb\Scripts\activate` instead. You can read more on that on the official virtualenv docs: [User guide: activate script](https://virtualenv.pypa.io/en/legacy/userguide.html#activate-script).

Alternatively, if you've got anaconda/miniconda installed you can create the environment for CellPhoneDB using that.
