### ISSUE TITLE
pvals

### ISSUE THREAD

**Issue by chrsyl** [Teichlab/cellphonedb#261]
In your instruction pvals is examplified with ther value 0.01. But I get only 1.0 - 0.1 and then 0. So why not more than one decimal? Could I interprete 0 as significant?

**Comment by jmrussell** [comment]
Check the value you used for 

--result-precision

**Comment by prete** [comment]
As mentioned, check 
- `--result-precision` (default is 3 digits)
- `--pvalue` for statistical analysis (default pvalue threshold is 0.05)
