### ISSUE TITLE
ligand_receptor or receptor_ligand?

### ISSUE THREAD

**Issue by chrsyl** [Teichlab/cellphonedb#265]
While ligand_receptor annotation is the norm, why does cellphonedb also annotate as receptor_ligand?  For example if I plot  celltype A|celltype B & celltype B|celltype A, there can be FLT1_VEGFB for A|B BUT NOT VEGFB_FLT1 FOR B|A.

**Comment by luzgaral** [comment]
CellphoneDB also includes other cell-cell interactions other than Ligand/Receptors, such as integrins, which do not have a direction in the signalling. That is why the order (ligand_receptor or receptor_ligand) is ignored. 

Hope it makes sense.
