### ISSUE TITLE
How to add some proteins and interactions

### ISSUE THREAD

**Issue by martin-jeremy** [Teichlab/cellphonedb#267]
Hi,
I'm beginning to work with scRNA seq for my internship, and I have to characterize some interactions between cells.
I install and compute easily a first analysis with Cellphonedb (thank's for the clear documentation !), but some interactions and proteins of interest are missing.

I downloaded the example of user_proteins and user_genes, then I found in this issue ( #185 ) that I can use the "Interaction input file" as custom_interaction. But how can I define new unique ID for proteins and interactions that I want to add ?

For instance, we can see in literature that Mrgprb2 (MRGPRX2 ortholog) interact with some peptide like Vip or substance P. So I wish add an interaction between Mrgprb2 and Vip in one hand, and add Tac1 (precursor of substance P), then the interaction between Mrgprb2 and Tac1 in the database in an other hand.

Any suggestion to realise this properly ?

Thank's for your help !

**Comment by luzgaral** [comment]
Hi,

Check out this: https://github.com/Teichlab/cellphonedb#generating-user-specific-custom-database
