### ISSUE TITLE
Are counts filtered?

### ISSUE THREAD

**Issue by suhasaii** [Teichlab/cellphonedb#272]
I am using scRNA data with hgnc_genesymbols and count data as a input to cellphonedb. It gives error at validation "All counts filtered: Are you using human data?"
<img width="893" alt="Screen Shot 2021-02-23 at 1 23 04 PM" src="https://user-images.githubusercontent.com/73250895/108910126-47a13680-75da-11eb-8253-26dc0edc943a.png">

![issue1](https://user-images.githubusercontent.com/73250895/108910006-1e80a600-75da-11eb-9b31-3bfea7d7c09a.png)

**Comment by nsleep** [comment]
Hi, something might be helpful. From #18 .
> CellPhoneDB works only with human ensembl ids, that's why all the genes are filtered out. You would need to convert the gene names into ensembl ids and input that into the method.

OR
> Did you use the parameter --counts-data=gene_name when you run it?
 
Best,
suhasaii

**Comment by prete** [comment]
@suhasaii did you manage to run it using `--counts-data=gene_name` ?

**Comment by prete** [comment]
Closed due to inactiviity. 

"All counts filtered: Are you using human data?" usually refers to either a wrong counts file format or using the wrong gene identifier (default is ensembl but can be changed to HGNC using the `--counts-data` option.)
