### ISSUE TITLE
Input data Question

### ISSUE THREAD

**Issue by jefferyUstc** [Teichlab/cellphonedb#279]
Hi, cellphonedb team,
I'd like to know what kind of data should feed as the input data. the raw counts, the normalized or log-normalized data?

**Comment by luzgaral** [comment]
From the paper: 
"Counts file. scRNA-seq count data containing gene expression values in which rows are genes presented with gene names identifiers (Ensembl IDs, gene names or hgnc_symbol annotation) and columns are cells. We recommend using normalized count data. Importantly, the user needs to specify whether the data was log-transformed when using the subsampling option. "
