### ISSUE TITLE
 Counts values are not decimal values. Incorrect file format !

### ISSUE THREAD

**Issue by wuzhigui** [Teichlab/cellphonedb#283]
![image](https://user-images.githubusercontent.com/70992194/110458797-2460a600-8107-11eb-911b-fd8fea037a68.png)
This is my format :
![image](https://user-images.githubusercontent.com/70992194/110458881-3e01ed80-8107-11eb-8c0a-32e542929d34.png)
Who will help me ?

**Comment by prete** [comment]
Hi @wuzhigui for what I see, you're using `sed -i 's/,/\t/g' CC_EC_assaymatrix.csv` before running cellphonedb. That changes the file from a CSV (which uses `,` for delimiter) to a TSV (which uses or `\t` — tab), if you want cellphonedb to pick that up, you probably need to change the file extension to `.tsv`.
 
Could you try renaming `CC_EC_assaymatrix.csv` to `CC_EC_assaymatrix.tsv` and trying again?

**Comment by wuzhigui** [comment]
thanks !



---Original---
From: ***@***.***&gt;
Date: Tue, Mar 9, 2021 21:37 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Teichlab/cellphonedb]  Counts values are not decimal values. Incorrect file format ! (#283)




 
Hi @wuzhigui for what I see, you're using sed -i 's/,/\t/g' CC_EC_assaymatrix.csv before running cellphonedb. That changes the file from a CSV (which uses , for delimiter) to a TSV (which uses or \t — tab), if you want cellphonedb to pick that up, you probably need to change the file extension to .tsv.
 
Could you try renaming CC_EC_assaymatrix.csv to CC_EC_assaymatrix.tsv and trying again?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
 
---Original---
From: ***@***.***&gt;
Date: Tue, Mar 9, 2021 21:37 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Teichlab/cellphonedb]  Counts values are not decimal values. Incorrect file format ! (#283)




 
Hi @wuzhigui for what I see, you're using sed -i 's/,/\t/g' CC_EC_assaymatrix.csv before running cellphonedb. That changes the file from a CSV (which uses , for delimiter) to a TSV (which uses or \t — tab), if you want cellphonedb to pick that up, you probably need to change the file extension to .tsv.
 
Could you try renaming CC_EC_assaymatrix.csv to CC_EC_assaymatrix.tsv and trying again?
