### ISSUE TITLE
input file format

### ISSUE THREAD

**Issue by ysu2015** [Teichlab/cellphonedb#287]
Hi, 

I was wondering what is the format for the input files (.txt) for cellphonedb. 
I tried .csv, which sep by "," or .txt, which sep by " ". All give me error.
Thank you so much.

Y

**Comment by prete** [comment]
Hi @ysu2015, `.txt` file separator is `\t` (tab).
Could you describe the errror you're getting or provide a sample of the file that's giving you the error?

**Comment by ysu2015** [comment]
HI Prete,
Thank you for your quick reply. I reformated my input file to use "\t" as sep. It works.  The program run. 
Thank you so much.

Y
