### ISSUE TITLE
used in plant

### ISSUE THREAD

**Issue by liuyongming0612** [Teichlab/cellphonedb#290]
hi guys
     I want to know whether this software supports the needs of plant research 
many thanks

**Comment by prete** [comment]
Hi @liuyongming0612 CellPhoneDB database has been manually curated only considering human interactions. The accuracy for any species can't be guaranteed. Any input from users is welcome, so if you've got something particular in mind please use the contact form from the website https://www.cellphonedb.org/contact-us
