### ISSUE TITLE
Error when generating dot plots with cellphone DB

### ISSUE THREAD

**Issue by aliciahillturner** [Teichlab/cellphonedb#291]
Hi there! I am having trouble generating dot plots in cellphonedb on my LINUXOS!
I have ensured I properly installed Python, activated my environment using conda, downloaded the sample data provided and also downloaded the required R package ggplot2 (which says it is installed). However, I keep getting this error and the plot won't generate.

![image](https://user-images.githubusercontent.com/73973890/112860115-8581f680-9081-11eb-9a66-59324154a139.png)

Any help is greatly appreciated!

**Comment by prete** [comment]
Hi @aliciahillturner, I can't say I know what caused that "Error in continuous_scale". How did you created your environment?  Could you try using the method described [in this comment](https://github.com/Teichlab/cellphonedb/issues/289#issuecomment-806766448) on #289 to create a clean conda environment? 

_(Note: if you already had one conda environment named `cpdb` I'd suggest you remove it first with `conda remove -n cpdb --all --yes`)

**Comment by aliciahillturner** [comment]
Thank you so much! Yes the other method you linked worked!!
