### ISSUE TITLE
"Error Invalid Counts Data"

### ISSUE THREAD

**Issue by aliciahillturner** [Teichlab/cellphonedb#292]
Hi there! I can successfully run CellphoneDB with the sample data provided on my Linux OS. However, when I run my own code I get an error with my counts file! I have specified --counts-data=gene_name as I am not using ensemble IDS but I still seem to get an error!

Here is a screenshot of my counts file for reference if it helps!

[](url)
![image](https://user-images.githubusercontent.com/73973890/112904999-bc72ff00-90b7-11eb-9b2e-a396b3c38b51.png)

Any help is appreciated as I am very new to this!

**Comment by prete** [comment]
Hi @aliciahillturner what's the extension on your count file? could you provide the full command you used?
Also, the use of normalised counts is recommended.

**Comment by aliciahillturner** [comment]
Hi Prete! The extension of my count file is .txt, full filename is patient21counts.txt , and I believe the data was already normalized through the Seurat Package using SCTransform in R?
Below is my command:
"cellphonedb method statistical_analysis patient21meta.txt patient21counts.txt –-counts-data=gene_name"

Hope this helps to make things more clear!

**Comment by prete** [comment]
I wanted to check that the file is `.txt` and has `\t` as separator. I can suggest you try using a subset of your `patient21counts.txt` data to rule out any mislabeled gene names. 

Does the error mention something else beside "Error Invalid Counts Data" ? Could you provide a sample of your input count file so I can test this and try to reproduce the error?

**Comment by prete** [comment]
Hi @aliciahillturner looks like the count matrix got pasted two times in the file. The header is duplicated at line `16118` and all the data after that. That's probably what's causing your issue.

**Comment by aliciahillturner** [comment]
Hi @prete, I updated my counts file to correct for that error. The new counts file is linked [here](https://drive.google.com/file/d/18C4iQ0JvdorQqhEx7Zrn-deW83BmOy0k/view?usp=sharing)

However, I still seem to get this error:
 [ERROR] Invalid Counts data: Some cells in meta didnt exist in counts columns. Maybe incorrect file format.
Is that just because I don't have all the cells in the meta clusters (i.e. Macrophage2 cluster) present in my counts file?

My meta file is also linked [here](https://drive.google.com/file/d/1TEcwW0rdl2WxtH2b0sP8auXpSLQ7DqRo/view?usp=sharing) for reference.

**Comment by prete** [comment]
> Hi @prete, I updated my counts file to correct for that error. The new counts file is linked [here](https://drive.google.com/file/d/18C4iQ0JvdorQqhEx7Zrn-deW83BmOy0k/view?usp=sharing)
>

The shared file is still wrong, but I guess you're working with a fixed one. 

> [ERROR] Invalid Counts data: Some cells in meta didnt exist in counts columns. Maybe incorrect file format.
> 

I think your issue is that **none** of the barcodes in your meta are present as columns in your count file.

**Comment by aliciahillturner** [comment]
Thanks @prete it works now and I am able to generate my plots and complete the analysis! Thanks for all your help :)

**Comment by xiaoxiaofuyou** [comment]
> 

hello, dear authors, i met the same problem, but i don't know how to solve this, could you please to help me to solve this problem, apprecita it!

![image](https://user-images.githubusercontent.com/105490459/175271719-03c3ba8e-db91-4315-8795-0a3e2f6bfd3c.png)
