### ISSUE TITLE
Missing interaction pair

### ISSUE THREAD

**Issue by balthasar0810** [Teichlab/cellphonedb#293]
Hi,

I do not see the pair IL18_IL18R1 in any of the CPDB outputs. I have cells expressing both genes (autocrine and paracrine). I already lowered --threshold to a super low number but still not present.

What am I missing? Any ideas??

Thanks, Chris

**Comment by QqQss** [comment]
I have found that there are two rows recording "IL18" in the deconvoluted.txt file. The former one had very low expression. Maybe this is the cause of the issue?
![image](https://user-images.githubusercontent.com/12655466/118920945-e0411b80-b969-11eb-8e63-c2ffb9975e73.png)

**Comment by luzgaral** [comment]
Hi,

Thank you both for pointing this out.
IL18 has been wrongly included as part of IL18_receptor complex. We'll fix this in our next release of the database.

Best
