### ISSUE TITLE
Error: Invalid value for "--columns": Path "in/columns.txt" does not exist.

### ISSUE THREAD

**Issue by aliciahillturner** [Teichlab/cellphonedb#294]
I am trying to run the command using the below code provided:
cellphonedb plot dot_plot --columns in/columns.txt

I can run and generate the total dot plot fine (see [here](https://drive.google.com/file/d/18RXZZg5004jVr0yXO3JB1U-uSf7QcFIa/view?usp=sharing)), however when I try to say " --columns in/columns.txt" I get the error "Error: Invalid value for "--columns": Path "in/columns.txt" does not exist."
[](url)
I am not sure if this is a path error or a cellphoneDB error, but my columns.txt file (linked [here](https://drive.google.com/file/d/1QR6eo_ZiRtkc2k2IpscYgAQy_Hlgpb6X/view?usp=sharing)) is in the same directory as my other files and has the correct information. I am also running this on Linux not sure if that matters?

My goal is to look at the interactions between specific clusters (i.e Macrophage1|Ductal1) but I keep running into this error!

**Comment by prete** [comment]
The error says that `Path "in/columns.txt" does not exist.`, are you sure that path is correct? May be your `columns.txt` file lives in the same folder that you're running the plotting command from, in that case it should be `cellphonedb plot dot_plot --columns columns.txt`

**Comment by aliciahillturner** [comment]
thank you! It worked :)
