### ISSUE TITLE
The cellphonedb running weird error 

### ISSUE THREAD

**Issue by honghh2018** [Teichlab/cellphonedb#295]
Hi @All,
     Thanks to develop the great tools.
      I got  some weird issue when running the cellphonedb to analyze my data,
      The inputed metadata.tsv like below:
       the metadata had three type:EPCAM-neg,EPCAM-pos and Fibroblasts
![image](https://user-images.githubusercontent.com/41668708/113399843-7a0d3300-93d3-11eb-8dff-0e73e280f8fc.png)
       The inputed matrix.tsv like below:
        the number of metadata.tsv 's barcode are identical with matrix.tsv file columns 
![image](https://user-images.githubusercontent.com/41668708/113399981-ade85880-93d3-11eb-8eed-815f398e3b8e.png)
        The running shell like below:
         cellphonedb method statistical_analysis --project-name tissue --iterations 1000 --threshold 0.2 --result-precision 3 --output-path outs2/cellphone --verbose --threads 14 metadata.tsv matrix.tsv
        The error post below:
        
![image](https://user-images.githubusercontent.com/41668708/113400342-38c95300-93d4-11eb-8664-d95183053fca.png)
![image](https://user-images.githubusercontent.com/41668708/113400382-4a125f80-93d4-11eb-9237-75dd3e4ec62f.png)
![image](https://user-images.githubusercontent.com/41668708/113400419-5bf40280-93d4-11eb-88cd-98c02e3176bb.png)
The error information was complexed and how can i fix this issue ?
 any advice would be appreciated.
  hanhuihong

**Comment by prete** [comment]
Hi @honghh2018 the errors are a bit confusing, specially because the command you say you ran is: 
> cellphonedb method statistical_analysis --project-name tissue --iterations 1000 --threshold 0.2 --result-precision 3 --output-path outs2/cellphone --verbose --threads 14 metadata.tsv matrix.tsv

and the last error shows a different command being invoked:
> Usage: cellphonedb plot dot_plot

Are all this errors from the same command?
Could you tell me how did you create the environment to run this? was it venv or conda? 
What's your version of cellphonedb and pandas? (`pip show cellphonedb pandas`)

**Comment by honghh2018** [comment]
Hi @prete ,
    It sorry to reply this late.
    the cellphonedb plot dot_plot was the subsequently step on my  wrapper pipeline of cellphonedb  the cellphonedb.
    In my case,  this error was shown up on step one, the pvalue.txt and means.txt generated. because of the step one had no successful, it triggerred the  cellphonedb plot error as well. just like i post above. the step one cannot get through.
   
![image](https://user-images.githubusercontent.com/41668708/113803910-10ed3d00-9790-11eb-894e-3828e05320e6.png)

    why the step one can not be run ?
     Any advice would be appreciated.
     hanhuihong

**Comment by honghh2018** [comment]
Can anybody hear this ?

**Comment by honghh2018** [comment]
I run it again, it show me below error
![image](https://user-images.githubusercontent.com/41668708/113991850-70794480-9885-11eb-98ef-3ce651642c63.png)
But i assure that the rowname had no duplication 
any advice would be appreciated

**Comment by prete** [comment]
Update CellphoneDB and downgrade your pandas version to fix this issue.

First upgrade Cellphone DB to the latest version:
`pip install -U cellphonedb`

Then make sure your pandas version is `pandas>=1.0.0,<=1.1.4` (that means higher than 1.0.0 and lower or equal to 1.1.4. If it's not you need to downgrade it to the correct version using: `pip install -U pandas==1.1.4`

That will solve your porblem.

**Comment by honghh2018** [comment]
Excellent! It work.
Cellphonedb updated later, the data could run well.
Thanks
