### ISSUE TITLE
P-Value Thresholding for Dot-Plot 

### ISSUE THREAD

**Issue by aliciahillturner** [Teichlab/cellphonedb#296]
I am trying to only show interactions with large circle diameters (i.e. significant interactions), therefore I want my dotplot to filter out any pvalues greater than 0.001 (for example). However, when I run the below code I still generate a dotplot that includes the non significant interactions (see dot plot below). 

cellphonedb method statistical_analysis patient21meta.txt T21counts.txt --counts-data=gene_name --iterations=10 --threads=2 –-pvalue=0.001

![image](https://user-images.githubusercontent.com/73973890/113419029-9d64bd80-9394-11eb-9f2d-407d4e927944.png)

Any help would be greatly appreciated as I am unsure what I am doing wrong with respect to p-value thresholding! :)

**Comment by prete** [comment]
Hi @aliciahillturner I may be getting your question wrong, but I think your figure looks as expected. If you want something else fileterd, you'll probably have to edit `means.txt` and `pvalues.txt` to get a different plot. Is there a row there you think it should not be included in the plot?

**Comment by Pedramto89** [comment]
Hello @prete 
I want to do the same. I mean to insert a threshold for pvalue. For example greater and/or equal to 0.05. What's the command:
Is sth like this:

ellphonedb method statistical_analysis meta_subtype2new.txt counts_subtype2new.txt --counts-data=hgnc_symbol --pvalue>0.05

When I use the above command, I get the following error:
Error: --pvalue option requires an argument
