### ISSUE TITLE
No such command "plot".

### ISSUE THREAD

**Issue by XinWang19** [Teichlab/cellphonedb#299]
Hi, 
I am a windows user. When I try to perform dotplot using the example dataset, I met this error showing no command "plot". And I found there were only 2 command "method" and "query" in cellphonedb. Thus, how to call "plot" in windows? Thanks a lot!
####################################
(cpdb) C:\Users\Xin\Downloads\cellphonedb_example_data\example_data\out>cellphonedb plot dot_plot
Usage: cellphonedb [OPTIONS] COMMAND [ARGS]...

Error: No such command "plot".
####################################
(cpdb) C:\Users\Xin\Downloads\cellphonedb_example_data\example_data\out>cellphonedb
Usage: cellphonedb [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  method
  query
####################################

**Comment by bioguy2018** [comment]
I assume you are using the older version of cellphondb, you can check the version you are currently using and if it is not updated then I suggest that you explicitly download the updated version and install through .tar file.
Somehow when you use pip install cellphonedb it downloads all version and install one of the older ones rather than the new one

**Comment by prete** [comment]
Hi @XinWang19 could you confirm the CellPhoneDB (`pip show cellphonedb`) installed on your system?

**Comment by XinWang19** [comment]
> Hi @XinWang19 could you confirm the CellPhoneDB (`pip show cellphonedb`) installed on your system?

Yes, it is. Following is the information.

C:\Users\Xin>conda activate cpdb

(cpdb) C:\Users\Xin>pip show cellphonedb
Name: CellPhoneDB
Version: 1.1.0
Summary: UNKNOWN
Home-page: https://cellphonedb.org
Author: YDEVS CONSULTING
Author-email: hi@ydevs.com
License: MIT
Location: c:\users\xin\anaconda3\envs\cpdb\lib\site-packages
Requires: pandas, PyYAML, click, SQLAlchemy, flask, requests, Flask-Testing, Flask-RESTful
Required-by:

**Comment by XinWang19** [comment]
> I assume you are using the older version of cellphondb, you can check the version you are currently using and if it is not updated then I suggest that you explicitly download the updated version and install through .tar file.
> Somehow when you use pip install cellphonedb it downloads all version and install one of the older ones rather than the new one

Thanks a lot. My cellphonedb version (conda source) is 1.1.

**Comment by prete** [comment]
> > I assume you are using the older version of cellphondb, you can check the version you are currently using and if it is not updated then I suggest that you explicitly download the updated version and install through .tar file.
> > Somehow when you use pip install cellphonedb it downloads all version and install one of the older ones rather than the new one
> 
> Thanks a lot. My cellphonedb version (conda source) is 1.1.

Please update with `pip install -U cellphonedb` and that should get you the latest version.
