### ISSUE TITLE
ValueError: cannot reindex from a duplicate axis

### ISSUE THREAD

**Issue by HichamAffia** [Teichlab/cellphonedb#3]
Dear all,
I try to use the package with my own data but I keep encountering this error while running "_cellphonedb method statistical_analysis clusters.txt matrice.txt_".

I checked my files and they are concordant to the example files, when I run a _head file.txt_ on the terminal, the only difference is that my cell type are numerics, corresponding to the clusters numbers, could it be the issue?

It happens at the _Building Simple results_ step.

Thank you!

**Comment by huang-ying** [comment]
Same problem here, I also tried to remove duplicate gene symbols in my table and still got the same problem. My cell type are all characters, while there are "-" and numerical values in my cell id.

 Here is the header lines or my error messages.
return callback(*args, **kwargs)
  File "/miniconda2/envs/cellphonedb/lib/python3.6/site-packages/cellphonedb/src/api_endpoints/terminal_api/method_terminal_api_endpoints/method_terminal_commands.py", line 82, in analysis
    **deconvoluted_result_name**,

**Comment by mvento** [comment]
Hi @HichamAffia,

`corresponding to the clusters numbers, could it be the issue` can be an issue. We will try to replicate your issue. Can you send us your inputs? (or part of that)

Thanks

**Comment by HichamAffia** [comment]
Hi @mvento ,

Here is a subset that gives me the same error. 
[input_subset_issue_3.zip](https://github.com/Teichlab/cellphonedb/files/2605878/input_subset_issue_3.zip)

Thanks

**Comment by mvento** [comment]
@HichamAffia Thanks, we try to check it ASAP.

Thanks for your patiente

**Comment by hejian41** [comment]
Also encountered the same problem, is there any solutions?   @HichamAffia 

Here are  error messages.
 ....... 
 File "/home/hejian/cpdb-venv/lib/python3.6/site-packages/pandas/core/internals.py", line 4414, in reindex_indexer
    self.axes[axis]._can_reindex(indexer)
  File "/home/hejian/cpdb-venv/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3576, in _can_reindex
    raise ValueError("cannot reindex from a duplicate axis")
ValueError: cannot reindex from a duplicate axis

**Comment by mvento** [comment]
Hi @HichamAffia,

This is because all data is filtered (we only support human genes yet).

We fix this crash in the next release.

Cheers

**Comment by mvento** [comment]
Hi @hejian41,

can you send your input data (or a part of that) to miquel@ydevs.com for debug purposes?

Thanks

**Comment by hejian41** [comment]
I checked my data and find there were some duplicated rownames. No error reported after the those genes were removed! @mvento

Thanks !

**Comment by mvento** [comment]
hi @hejian41, 

Perfect! we are working on better error reporting.

Cheers

**Comment by HichamAffia** [comment]
Hi @mvento , thanks!

**Comment by saeedfc** [comment]
Same error here for me! All my Genes are human ensemble IDs and are unique. Any solutions yet?

**Comment by mvento** [comment]
Hi @saeedfc, 

We are working on a better error report. Can you send us your data (or a part of that) to us? 

Thanks!

**Comment by saeedfc** [comment]
HI @mvento , 

It was again an issue of R giving an extra column for serial numbers as rownames. I removed it and then ran it. Went fine.

**Comment by mvento** [comment]
Hi all, 

We have released the version v.1.1.0 of CellPhoneDB. These errors are checked now to prevent app crash. 

We have added error messages and we are working on a better documentation of the errors to help to the user.

Thanks for using CellPhoneDB!
