### ISSUE TITLE
bulk RNA-SEQ dataset

### ISSUE THREAD

**Issue by bioguy2018** [Teichlab/cellphonedb#300]
Dear developers,
Can CellphoneDB in principal be applied to bulk rna-seq data? if yes what I should bear in mind for the analysis 

Thank you

**Comment by jariwalask** [comment]
How are you planning on defining clusters? Cell types through deconvolution?

**Comment by bioguy2018** [comment]
Hi,
My cell types are already defined prior to the experiment. I have two set of samples each belonging to a different cell types and they have been sequenced.

**Comment by luzgaral** [comment]
Hi,

CellphoneDB requires single-cell unit. You will need to find a way to move from your cell type-specific bulk data to a single cell-like dataset.

One option is to consider each replicate in each set of samples as a pseudo single cell. Bear in mind that you will need a few replicates as in single cell we expect at least 50 cells per cell type.

Hope this helps,

Luz
