### ISSUE TITLE
Invalid Counts data

### ISSUE THREAD

**Issue by YuliaInn** [Teichlab/cellphonedb#306]
I have normalized my data in Seurat using "RC" method. Here is a subset of my count data. I also converted all the gene names into ensemble ids. 

My command is 
`cellphonedb method statistical_analysis metadata_LEFT.txt countsLEFT.txt --threads=6`

I get an error "Invalid Counts data"
[sample_1.txt](https://github.com/Teichlab/cellphonedb/files/6423652/sample_1.txt)

**Comment by prete** [comment]
Hi @YuliaInn your sample looks OK. Questions that come to mind are:
- which version of CellPhoneDB and pandas are you using? (`pip show cellphonedb pandas`)
- are all cells from your meta file in your counts file?
- do you have enough memory to run this?

**Comment by YuliaInn** [comment]
I used cellphone environment that somebody posted here in issues. 

The content of environment.yml is:

name: cellphone
dependencies:
  - python=3.7.9
  - r-base
  - r-pheatmap
  - pip
  - pip:
    - cellphonedb
    - scikit-learn==0.20.4

My meta file is attached and the cell names look like they match the count's cell names. 

I am running this in hpc cluster, I usually get a memory outage error. But in cellphonedb I have only "Invalid Counts data" error (screenshot of an error is attached

thank you!

![Screen Shot 2021-05-05 at 11 38 35 AM](https://user-images.githubusercontent.com/54861076/117177639-e0042600-ad96-11eb-990f-d03829499109.png)
)
[cellphonedb_metaLEFT.txt](https://github.com/Teichlab/cellphonedb/files/6428676/cellphonedb_metaLEFT.txt)

**Comment by prete** [comment]
Both meta and counts look fine. Actually, meta has some extra columns (it should only have two) but that shouldn't be an issue.

I can suggest that you re-try this with only a fraction of your counts file (about 30%) to see if it works properly. Should that go well, then it's probably a memory issue and you need to request more when you submit a job to your HPC (don't know how much really, but start with something like 30GB RAM?)

Also, could you please check both the version of cellphonedb/pandas you've got in your environment (`pip show cellphonedb pandas`)?

**Comment by YuliaInn** [comment]
I tried to run cellphonedb on just 500 cells and still got the same error.
Here are the cellphonedb and pandas info:

Name: CellPhoneDB
Version: 2.1.4
Summary: UNKNOWN
Home-page: https://cellphonedb.org
Author: TeichLab
Author-email: contact@cellphonedb.org
License: MIT
Location: /storage/hpc/data/iid49/miniconda/envs/cellphone/lib/python3.7/site-packages
Requires: click, flask, requests, Flask-Testing, boto3, geosketch, PyYAML, Flask-RESTful, rpy2, cython, tqdm, pika, SQLAlchemy, pandas
Required-by: 
---
Name: pandas
Version: 0.23.4
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: http://pandas.pydata.org
Author: None
Author-email: None
License: BSD
Location: /storage/hpc/data/iid49/miniconda/envs/cellphone/lib/python3.7/site-packages
Requires: python-dateutil, pytz, numpy
Required-by: CellPhoneDB

**Comment by prete** [comment]
Looks like you're using an old CellPhoneDB version, could you update to v2.1.7 (`pip install -U CellPhoneDB`) and try agan?

**Comment by YuliaInn** [comment]
thank you for your prompt responses. I found an extra column in my normalized counts data and deleted it. Now it works
