### ISSUE TITLE
dot_plot figure parameters

### ISSUE THREAD

**Issue by eijynagai** [Teichlab/cellphonedb#311]
Hi,

First, thank you so much for the CellPhoneDB!! It's awesome!

I only have a small question. Would it be possible to change the font size and or scale of the plots?? Is it using matplot or other or other package? And if so, would you please tell me how.

I have a long list of genes and it would be nice to increase the font size a little bit.

Best regards,

Nagai

**Comment by eijynagai** [comment]
Oh, just saw in the [documentation](https://github.com/Teichlab/cellphonedb#plotting-statistical-method-results) that is in R ggplot and not python. 

I tried checking if there is anything that can be done but no success. 
Could you please let me know if there is anything that could be done to modify the plots??

**Comment by eijynagai** [comment]
Found it, [here](https://github.com/Teichlab/cellphonedb/blob/master/cellphonedb/src/plotters/R/plot_dot_by_column_name.R) in the source code... sorry for bothering! I can modify myself there! 

Thanks for the tool. Closing this issue.

**Comment by prete** [comment]
The method for running the plotting scripts manually is [described here](https://github.com/Teichlab/cellphonedb/issues/286#issuecomment-822349683).
