### ISSUE TITLE
The barcodes changes when using data.frame 

### ISSUE THREAD

**Issue by chenxofhit** [Teichlab/cellphonedb#312]
test_counts <- as.matrix(dha.subset@assays$RNA@data)
head(test_counts) then it ouputs:

![image](https://user-images.githubusercontent.com/1176815/118748079-c500de00-b88d-11eb-97db-1b553148ce6c.png)

and :
test_counts <- as.matrix(dha.subset@assays$RNA@data)
test_counts <- data.frame(Gene=rownames(test_counts), test_counts,stringsAsFactors = F)
I append the first column named Gene for further mice gene name  transferring to human gene name in my case.
head(test_counts) then it outputs:
![image](https://user-images.githubusercontent.com/1176815/118748213-05f8f280-b88e-11eb-8fa2-984cb38b3799.png)

When looking carefully, the cell barcodes changes  from AAACCCAAGGAGTATT-1_3 to AAACCCAAGGAGTATT.1_3, what causes this result? Maybe the issue should not be here, but I wonder if anyone know.

**Comment by prete** [comment]
Hi @chenxofhit I fail to see how this issue relates to CellPhoneDB, could you explain?

**Comment by chenxofhit** [comment]
Yes，this issue does not relate to this topic. This issue occurs when I conduct an experiment with CellPhoneDB.  I also attach a link to the Seurat repository.

**Comment by chengying33** [comment]
> Yes，this issue does not relate to this topic. This issue occurs when I conduct an experiment with CellPhoneDB. I also attach a link to the Seurat repository.

I got the same problem. Did you fix it then?

**Comment by chenxofhit** [comment]
> > Yes，this issue does not relate to this topic. This issue occurs when I conduct an experiment with CellPhoneDB. I also attach a link to the Seurat repository.
> 
> I got the same problem. Did you fix it then?
please see: https://github.com/satijalab/seurat/issues/4492#issuecomment-846012590
