### ISSUE TITLE
How to make the heatmap plot with row names in order?

### ISSUE THREAD

**Issue by ilyiaZhao** [Teichlab/cellphonedb#319]
I notice that there is no function to order the row and column names in decreasing order when plotting heatmap.
What can I do for that?
Because I am comparing the cell and cell interactions among different condition. So it's better to have the rows in the same order.
So what can I do for getting my goal?

**Comment by prete** [comment]
At this point I don't have an already tested solution, but, the source code for plotting heatmap is here: https://github.com/Teichlab/cellphonedb/blob/master/cellphonedb/src/plotters/R/plot_heatmaps.R

To achieve what you're after you can manually run that R script (passing all the parameters needed). Once you can do that, then you can edit the code the use something like the [order](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/order) function to sort the matrix before plotting I guess.

**Comment by prete** [comment]
Duplicated of #246

**Comment by GangZoo1** [comment]
Hi,

Sorry for reopening this issue.
I have the same issue, ordering the heatmap.
I tried to use the order function to solve the issue

 #######   Network
  meta = read.csv(meta_file, comment.char = '', sep=meta_sep)
  meta<-meta[order(meta[2,])]

but this does nothing. Is there any other way to order a heatmap plot?
Thanks
