### ISSUE TITLE
Custom interaction list resulting in KeyError: 'partner_a'

### ISSUE THREAD

**Issue by sylvia-science** [Teichlab/cellphonedb#320]
Hello,

I'm trying to input my own interaction list. I'm running the following code on it:

cellphonedb database generate --user-interactions interaction_input.csv 

I get the resulting error. At first I thought something was wrong with how I inputted my genes, but I tried rerunning with only the first line of the interaction list downloaded from the website but it still gives the same error.
[](url)
File "/Users/u0144780/opt/anaconda3/envs/cpdb/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
raise KeyError(key) from err
KeyError: 'partner_a'

Here's the interaction input file.
[interaction_input.csv](https://github.com/Teichlab/cellphonedb/files/6598075/interaction_input.csv)

**Comment by prete** [comment]
Hi @sylvia-science you're using `;` as a separator character when you should be using `,` for csv files.
Alternatively you can change `;` for `\t` (TAB) and rename the extension of the file to`.tsv`

Your file should look like this:
```
id_cp_interaction,partner_a,partner_b,protein_name_a,protein_name_b,annotation_strategy,source
CPI-CC0041E1D30,IL12,IL12 receptor,,,curated,uniprot
```
