### ISSUE TITLE
Where is the count_network.txt file

### ISSUE THREAD

**Issue by TehseusKunka** [Teichlab/cellphonedb#331]
When I finish the process 'cellphonedb method statistical_analysis  cellphonedb_meta.txt  cellphonedb_count.txt      --counts-data=gene_name', the files in out did not include 'count_network.txt' and 'interaction_count.txt'.
Did I miss something?

**Comment by prete** [comment]
Those two files are generated by the heatmap plot process. You need to run `cellphonedb plot heatmap_plot yourmeta.txt` first first in order to get `count_network.txt` and `interaction_count.txt`.

**Comment by TehseusKunka** [comment]
> 
> 
> Those two files are generated by the heatmap plot process. You need to run `cellphonedb plot heatmap_plot yourmeta.txt` first first in order to get `count_network.txt` and `interaction_count.txt`.
THANKS VERY MUCH!
