### ISSUE TITLE
Do not get an output from statistical analysis

### ISSUE THREAD

**Issue by Pedramto89** [Teichlab/cellphonedb#336]
I tried to run the first commands of CPDB but I do not get any output file. 
I installed the latest version of cpdb on my ubuntu. 
![Screenshot from 2021-07-20 01-17-53](https://user-images.githubusercontent.com/85902042/126278435-a2a6f7bb-7d39-4027-8292-0068c382a022.png)

**Comment by prete** [comment]
Hi @Pedramto89 thank you for using CellPhoneDB. 

The results will be inside the `out` folder. But your issue probably is one of the following:
a) Your genes are not using ENSEMBL identifiers, in that case you should try adding the `--counts-data=hgnc_symbol`
b) The format of your meta or counts file is incorrect

**Comment by Pedramto89** [comment]
Yes it worked out by adding the hgnc_symbol
thank you
