### ISSUE TITLE
Partner A and Partner B delimiter query

### ISSUE THREAD

**Issue by GBeattie** [Teichlab/cellphonedb#337]
Hey,

I have two recent installs of cellphonedb, one in a venv and one locally, and I was surprised to see that the delimiter between partner A and B was a "|" in the output from one and a "_" in the other. I can't see a way to check the versions that I have, so I'm not certain I've got two different versions but that would explain it. 

If they are different versions which one is the most recent (maybe it doesn't make a notable difference)? On a side note I vote for the "|" delimiter since it's rarely used in cluster IDs, making processing the outputs a lot easier.

Thanks!

Gordon

**Comment by prete** [comment]
Hi @GBeattie thank you for using CellPhoneDB. The separator character in the latest version (2.1.7) is `|`, it was changed back in [May 2019](https://github.com/Teichlab/cellphonedb/commit/3e801624243d4a2611aa927675200a567dcd7781) with the release of CellPhoneDB v2.0.0.

**Comment by GBeattie** [comment]
Thanks for the reply, not quite sure how I ended up with such an old version...
