### ISSUE TITLE
Installation instructions result in CellphoneDB v1 being installed

### ISSUE THREAD

**Issue by GBeattie** [Teichlab/cellphonedb#338]
Hey,

I have followed the installation instructions (created a conda environment, 3.7, followed by pip install), and ran cellphonedb to find that the cluster delimiter was "_" rather than "|" (in reference to  #337), meaning v1 is installed. Any ideas of what the issue might be? I'm not hugely experienced with python, and I have cellphonedb v1 installed locally, but I would presume installing within the conda environment would have kept the versions separate?

Any assistance greatly appreciated! 

Thanks,
Gordon

**Comment by prete** [comment]
Hi @GBeattie, sorry for the confusion. Are we talking about the cluster separator or gene interaction separator? 
I'll go and double check but I'm pretty sure: cluster combinations use `|` and gene interaction pairs use `_`.  But just to be sure, could you please try `pip show cellphonedb` and check the version that was effectively installed?

**Comment by GBeattie** [comment]
I am referring to the cluster separator yes, and thanks for the command, it shows that it is a version issue. Below is the output, you can see I'm within the environment in which I installed cellphonedb following the instructions earlier.

```
(3.5.9/envs/cpdb) (base) gordon@eduroam-int-dhcp clust % pip show cellphonedb
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Name: CellPhoneDB
Version: 1.1.0
Summary: UNKNOWN
Home-page: https://cellphonedb.org
Author: YDEVS CONSULTING
Author-email: hi@ydevs.com
License: MIT
```

**Comment by prete** [comment]
Looks like you're still using python 3.5, you'll need *at least* python 3.6 for the latest version of CellPhoneDB.

When creating a conda env, I'd recommend you use this [environment.yml.txt](https://github.com/Teichlab/cellphonedb/files/6865341/environment.yml.txt) You use like this: 
`conda env create --file environment.yml.txt` and finally activate the environment `conda activate cpdb`

**Comment by GBeattie** [comment]
Great I have it working now, I discovered the problem was having multiple environments open since I failed to close them properly. Using `conda deactivate` a few times closed these, then reactivating the environment allowed it to find Python 3.8 and CellphoneDB v2. Thanks for the assistance!
