### ISSUE TITLE
Cannot read count.txt

### ISSUE THREAD

**Issue by zhouyutong123** [Teichlab/cellphonedb#341]
Hi, I'm getting errors " Can not read /Users/tong/Desktop/OIR/cellphone_count.txt"when trying to read the raw data from Seurat object ,here is my code"cellphonedb method statistical_analysis cellphonedb_meta.txt cellphone_count.txt" 
![image](https://user-images.githubusercontent.com/87084179/128426540-07daacf2-4425-4c63-8106-8cd5a7b21be3.png)
Can you please help me? Thanks!

**Comment by prete** [comment]
Hi @zhouyutong123 are you running the `cellphonedb method...` command from the same folder you've genearted the file in?
if not, you need to provide the full for it
```vash
cellphonedb method statistical_analysis /Users/tong/Desktop/OIR/cellphonedb_meta.txt /Users/tong/Desktop/OIR/cellphone_count.txt
```

**Comment by prete** [comment]
Hi @zhouyutong123 did using the full path solved your issue?

**Comment by prete** [comment]
This issue was closed because it has been inactive for too long.
