### ISSUE TITLE
Understanding how to use the database files and extract a simple ligand/receptor table

### ISSUE THREAD

**Issue by nathanin** [Teichlab/cellphonedb#342]
Hello, I'm looking for a simple table with curated ligand/receptor pairs (+ligands/receptor complexes composed of several gene products). Is it possible to create such a table from the files saved at `~/.cpdb/releases/v2.0.0` by the command `cellphonedb database download --version latest`? Thanks for all the great work creating this amazing resource!

**Comment by Zaein** [comment]
Did you ever figure this out @nathanin?

**Comment by nathanin** [comment]
@Zaein I haven't spent much time with this yet but there is this "omnipath" database that includes cellphonedb, and others and sounds straightforward to work with.

https://github.com/saezlab/omnipath
