### ISSUE TITLE
How are the mean values calculated in the Means.txt output file from CellphoneDB

### ISSUE THREAD

**Issue by julie-jch** [Teichlab/cellphonedb#345]
I apologize if this question is trivial. I ran the cellphoneDB program  on my data and it generated 4 output files. I'm looking at the mean and significant mean files and I'm trying to understand how the program calculates these values. Do you have a methods paper showing how the program generated these results after the meta and count files are inputted? 

I don't seem to get the same values when I doing this process manually so I'm trying to really understand how the values are calculated in the output files and what they mean.

**Comment by prete** [comment]
Hi @julie-jch  according to the docs the mean values for all the interacting partners (mean) value refers to the total mean of the individual partner average expression values in the corresponding interacting pairs of cell types. If one of the mean values is 0, then the total mean is set to 0. (Only in mean.txt)

You can also read more about that here:
- Database design, analysis method and results: https://www.cellphonedb.org/documentation
- Results documentation: https://github.com/Teichlab/cellphonedb/blob/master/Docs/RESULTS-DOCUMENTATION.md
- Directly in the code at the [mean_analysis](https://github.com/Teichlab/cellphonedb/blob/714bbbc7de9ea037c9852085db3cd6afdaba2fa4/cellphonedb/src/core/methods/cpdb_statistical_analysis_helper.py#L175) and [build_significant_means](https://github.com/Teichlab/cellphonedb/blob/714bbbc7de9ea037c9852085db3cd6afdaba2fa4/cellphonedb/src/core/methods/cpdb_statistical_analysis_helper.py#L428) functions.

Hope that helps.

**Comment by julie-jch** [comment]
Thank you very much. Much appreciated!
