### ISSUE TITLE
read meta and count file error

### ISSUE THREAD

**Issue by gevin-MB** [Teichlab/cellphonedb#348]
![image](https://user-images.githubusercontent.com/32149026/133395251-354dd953-8df6-4bae-b7bf-d33d1d7a77b3.png)

**Comment by prete** [comment]
Hi @gevin-MB can't say for sure without more information. Could you please provide more info on this like:
- The rest of the output message
- Command you used to launch cellphonedb
- Part of your meta/counts files
- CellPhoneDB version you're using (`pip show cellphonedb`)
