### ISSUE TITLE
P-value Format

### ISSUE THREAD

**Issue by julie-jch** [Teichlab/cellphonedb#349]
Hi team,
I was working with your results file and noted that p-values are rounded to 1 decimal place. 
Is there any way the actual p-values without any rounding can be obtained? 
Thanks in advance.

**Comment by prete** [comment]
Hi @julie-jch thank you for using CellPhoneDB. 
The rounding is handled by the `--result-precision` option when launching CellphoneDB, by default that value is 3. 
You probably only see 1 decimal place for results in pvalues.txt with a value of `1.0`, are you seen all values with only 1 decimal?
