### ISSUE TITLE
why the p values and mean values of clusterA-clusterB are different with the clusterB-clusterA?

### ISSUE THREAD

**Issue by zyan0626** [Teichlab/cellphonedb#359]
Hello! I think it is a great tool!
But I am curious why the p values and mean values of clusterA-clusterB are different with the clusterB-clusterA? 
Thank you!

**Comment by luzgaral** [comment]
Hello!

Thank you for using cellphoneDB :)

Please note that the interactions are not symmetric. Partner A expression is considered on the first cluster, and partner B expression is considered on the second cluster. In other words:
* clusterA_clusterB = clusterA expressing partner A and clusterB expressing partner B.
* clusterA_clusterB and clusterB_clusterA  values will be different.

See https://github.com/Teichlab/cellphonedb/blob/master/Docs/RESULTS-DOCUMENTATION.md

Luz
