### ISSUE TITLE
dot_plot cant show labels

### ISSUE THREAD

**Issue by lgmp315** [Teichlab/cellphonedb#369]
dear friend, I want 
![lQLPDhtIKHwXvjnNAyTNAzmw-mPORpzPoK4CRuWoVIAGAA_825_804](https://user-images.githubusercontent.com/98027401/160740219-0c9c5b44-afc0-4579-a81a-c9f0ea64fa60.png)
to know why the label of my drawing is square, I tried to reduce the number of gene lines but still can not solve  .

**Comment by prete** [comment]
@lgmp315 Do you get the same result when you use PNG (`plot.png`) or JPEG (`plot.jpeg`) as outputs? [see readme for dot_plot output formats ](https://github.com/Teichlab/cellphonedb#dot_plot)

Next thing you can try is running the script manually like suggested on https://github.com/Teichlab/cellphonedb/issues/301

Aditionally, we have updated CellPhoneDB to v3 and migted CellPhoneDB to a new repository. Please refer to [ventolab/CellphoneDB](https://github.com/ventolab/CellphoneDB) for the most up to date version and issue support.
