### ISSUE TITLE
Input error cellphonedb statistical analysis

### ISSUE THREAD

**Issue by MathiniVaikunthan** [Teichlab/cellphonedb#382]
Hello! I'm having trouble with the statistical analysis function because it is throwing an error with my inputs possibly being the wrong type but I think that the class of the metadata and the counts are what they should be? Counts are numeric, and metadata are characters. Any help would be much appreciated!
![New Note](https://user-images.githubusercontent.com/97636728/182637263-5f8de449-873d-481d-afa8-efb50c7943d1.jpeg)
![Cluster](https://user-images.githubusercontent.com/97636728/182637286-216ac9b5-7af1-4724-b787-d305615765ab.jpeg)
![class(counts_list 1 $Gene)](https://user-images.githubusercontent.com/97636728/182637310-5d3cd661-bab7-444c-908b-0331dc19e481.jpeg)
![New Note](https://user-images.githubusercontent.com/97636728/182637327-6d791379-f896-407f-821c-7c3317c75d3a.jpeg)

**Comment by lisbeth-dot-95** [comment]
The problem was resolved when I just pasted a "Cluster_" in front of the cluster numbers.

**Comment by prete** [comment]
We recommend clusters to be strings to prevent this specific issue in some environments. 
Like @lisbeth-dot-95 mentioned, prepending `Cluster_` (or any other string for that matter) should solve the issue.
