### ISSUE TITLE
Unsupported operand types

### ISSUE THREAD

**Issue by saeedfc** [Teichlab/cellphonedb#4]
`cellphonedb method statistical_analysis meta.txt celldb_counts.txt --project-name=CellPhoneDB10 --iterations=10`
I tried the above line of code. It was running for  a few seconds and I got this error
TypeError: ("unsupported operand type(s) for +: 'float' and 'str'", 'occurred at index ENSG00000107562').

Example file did not have an issue and was working fine.
I double checked my file formats and the example file. There seems to be no difference.

Any help is appreciated.
Thank you very much!

**Comment by mvento** [comment]
Hi @saeedfc,

Thanks for using CellPhoneDB. Can you send us your input or a part of that? It makes us easier to debug it.

Thanks!

**Comment by saeedfc** [comment]
@mvento Thanks for the reply. I have shared it with you on miquel@ydevs.com.
