### ISSUE TITLE
Input data 

### ISSUE THREAD

**Issue by justinesjw** [Teichlab/cellphonedb#40]
Hi, 

Thanks for the awesome tool!

I noticed that the text input data is count. 
Was wondering if TPM data will work the same?

Thanks!

**Comment by mief** [comment]
Hi,
Thanks for your interest in our tool!

Yes, we prefer count data, but the method will work on TPM as well. The only issue is that when we calculate % of cells in a cluster expressing a certain receptor/ligand, we consider >0 as expressed. With TPMs, there are often values between 0 and 1 which should probably not be considered. We will try to introduce this into our new version.

Best,
Mirjana
