### ISSUE TITLE
Inconsistent receptor-ligand order

### ISSUE THREAD

**Issue by ktravaglini** [Teichlab/cellphonedb#9]
Thank you for curating a list of protein receptor-ligand interactions, very helpful!

I noticed that the majority of interactions are listed as LIGAND_RECEPTOR in the database, but every now and then you run across the opposite.

Ex: Most of the Wnt interactions are WNT_FZD, but a few like FZD1_WNT3A are reversed.

Is it possible to make these consistent in a future release? Or Is there a simple way to pass a custom interaction list within the CLI?

Kyle

**Comment by aditisk** [comment]
Hi @mvento, is there any way yet for users to use a custom list of interactions ? @ktravaglini were you able to use a custom list yet or is that feature still upcoming ?

Thank you.

**Comment by mvento** [comment]
Hi @aditisk, 

Now you can use your custom list when you generate your custom database.

Please, update CellPhoneDB version and check the documentation:

https://github.com/Teichlab/cellphonedb#examples-for-user-specific-custom-database

Best
